//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("Codex.ResourceGenerator", "1.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class Resource
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resource()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource", typeof(Resource).Assembly);
                }

                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.PluginName.
    /// </summary>
    public static string PluginName {
        get {
            return ResourceManager.GetString("PluginName", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.PluginDescription.
    /// </summary>
    public static string PluginDescription {
        get {
            return ResourceManager.GetString("PluginDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.PageTitle.
    /// </summary>
    public static string PageTitle {
        get {
            return ResourceManager.GetString("PageTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.SettingsPageTitle.
    /// </summary>
    public static string SettingsPageTitle {
        get {
            return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.QuickActionsTitle.
    /// </summary>
    public static string QuickActionsTitle {
        get {
            return ResourceManager.GetString("QuickActionsTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.QuickActionsDescription.
    /// </summary>
    public static string QuickActionsDescription {
        get {
            return ResourceManager.GetString("QuickActionsDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.RunQuickOptimizationButton.
    /// </summary>
    public static string RunQuickOptimizationButton {
        get {
            return ResourceManager.GetString("RunQuickOptimizationButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ResetNetworkStackButton.
    /// </summary>
    public static string ResetNetworkStackButton {
        get {
            return ResourceManager.GetString("ResetNetworkStackButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.AdminHint.
    /// </summary>
    public static string AdminHint {
        get {
            return ResourceManager.GetString("AdminHint", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.PreferredModeTitle.
    /// </summary>
    public static string PreferredModeTitle {
        get {
            return ResourceManager.GetString("PreferredModeTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.SaveModeButton.
    /// </summary>
    public static string SaveModeButton {
        get {
            return ResourceManager.GetString("SaveModeButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ModeBalanced.
    /// </summary>
    public static string ModeBalanced {
        get {
            return ResourceManager.GetString("ModeBalanced", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ModeGaming.
    /// </summary>
    public static string ModeGaming {
        get {
            return ResourceManager.GetString("ModeGaming", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ModeStreaming.
    /// </summary>
    public static string ModeStreaming {
        get {
            return ResourceManager.GetString("ModeStreaming", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StatusQuickOptimizationCompleted.
    /// </summary>
    public static string StatusQuickOptimizationCompleted {
        get {
            return ResourceManager.GetString("StatusQuickOptimizationCompleted", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StatusQuickOptimizationFailed.
    /// </summary>
    public static string StatusQuickOptimizationFailed {
        get {
            return ResourceManager.GetString("StatusQuickOptimizationFailed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StatusResetCompleted.
    /// </summary>
    public static string StatusResetCompleted {
        get {
            return ResourceManager.GetString("StatusResetCompleted", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StatusResetFailed.
    /// </summary>
    public static string StatusResetFailed {
        get {
            return ResourceManager.GetString("StatusResetFailed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StatusSelectValidMode.
    /// </summary>
    public static string StatusSelectValidMode {
        get {
            return ResourceManager.GetString("StatusSelectValidMode", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StatusModeSaved.
    /// </summary>
    public static string StatusModeSaved {
        get {
            return ResourceManager.GetString("StatusModeSaved", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.SettingsTitle.
    /// </summary>
    public static string SettingsTitle {
        get {
            return ResourceManager.GetString("SettingsTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.SettingsDescription.
    /// </summary>
    public static string SettingsDescription {
        get {
            return ResourceManager.GetString("SettingsDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.AutoOptimizeOnStartup.
    /// </summary>
    public static string AutoOptimizeOnStartup {
        get {
            return ResourceManager.GetString("AutoOptimizeOnStartup", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ResetWinsockOnOptimize.
    /// </summary>
    public static string ResetWinsockOnOptimize {
        get {
            return ResourceManager.GetString("ResetWinsockOnOptimize", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ResetTcpIpOnOptimize.
    /// </summary>
    public static string ResetTcpIpOnOptimize {
        get {
            return ResourceManager.GetString("ResetTcpIpOnOptimize", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.SaveSettingsButton.
    /// </summary>
    public static string SaveSettingsButton {
        get {
            return ResourceManager.GetString("SaveSettingsButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.SettingsSaved.
    /// </summary>
    public static string SettingsSaved {
        get {
            return ResourceManager.GetString("SettingsSaved", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.LiveTelemetryTitle.
    /// </summary>
    public static string LiveTelemetryTitle {
        get {
            return ResourceManager.GetString("LiveTelemetryTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.LiveTelemetryDescription.
    /// </summary>
    public static string LiveTelemetryDescription {
        get {
            return ResourceManager.GetString("LiveTelemetryDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.CurrentDownloadLabel.
    /// </summary>
    public static string CurrentDownloadLabel {
        get {
            return ResourceManager.GetString("CurrentDownloadLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.CurrentUploadLabel.
    /// </summary>
    public static string CurrentUploadLabel {
        get {
            return ResourceManager.GetString("CurrentUploadLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.PeakTrafficLabel.
    /// </summary>
    public static string PeakTrafficLabel {
        get {
            return ResourceManager.GetString("PeakTrafficLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ActiveAdapterLabel.
    /// </summary>
    public static string ActiveAdapterLabel {
        get {
            return ResourceManager.GetString("ActiveAdapterLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.DownloadLegend.
    /// </summary>
    public static string DownloadLegend {
        get {
            return ResourceManager.GetString("DownloadLegend", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.UploadLegend.
    /// </summary>
    public static string UploadLegend {
        get {
            return ResourceManager.GetString("UploadLegend", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ChartEmptyState.
    /// </summary>
    public static string ChartEmptyState {
        get {
            return ResourceManager.GetString("ChartEmptyState", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.DownloadTotalLabel.
    /// </summary>
    public static string DownloadTotalLabel {
        get {
            return ResourceManager.GetString("DownloadTotalLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.UploadTotalLabel.
    /// </summary>
    public static string UploadTotalLabel {
        get {
            return ResourceManager.GetString("UploadTotalLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.UpdatedLabel.
    /// </summary>
    public static string UpdatedLabel {
        get {
            return ResourceManager.GetString("UpdatedLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.PreferredModeDescription.
    /// </summary>
    public static string PreferredModeDescription {
        get {
            return ResourceManager.GetString("PreferredModeDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.CurrentModeLabel.
    /// </summary>
    public static string CurrentModeLabel {
        get {
            return ResourceManager.GetString("CurrentModeLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ModeBalancedDescription.
    /// </summary>
    public static string ModeBalancedDescription {
        get {
            return ResourceManager.GetString("ModeBalancedDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ModeGamingDescription.
    /// </summary>
    public static string ModeGamingDescription {
        get {
            return ResourceManager.GetString("ModeGamingDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.ModeStreamingDescription.
    /// </summary>
    public static string ModeStreamingDescription {
        get {
            return ResourceManager.GetString("ModeStreamingDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StatusCardTitle.
    /// </summary>
    public static string StatusCardTitle {
        get {
            return ResourceManager.GetString("StatusCardTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.MonitoringStatus.
    /// </summary>
    public static string MonitoringStatus {
        get {
            return ResourceManager.GetString("MonitoringStatus", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.NoActiveAdapter.
    /// </summary>
    public static string NoActiveAdapter {
        get {
            return ResourceManager.GetString("NoActiveAdapter", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.MbpsValueFormat.
    /// </summary>
    public static string MbpsValueFormat {
        get {
            return ResourceManager.GetString("MbpsValueFormat", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.SettingsSummaryTitle.
    /// </summary>
    public static string SettingsSummaryTitle {
        get {
            return ResourceManager.GetString("SettingsSummaryTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.SettingsSummaryDescription.
    /// </summary>
    public static string SettingsSummaryDescription {
        get {
            return ResourceManager.GetString("SettingsSummaryDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StateEnabled.
    /// </summary>
    public static string StateEnabled {
        get {
            return ResourceManager.GetString("StateEnabled", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource.StateDisabled.
    /// </summary>
    public static string StateDisabled {
        get {
            return ResourceManager.GetString("StateDisabled", resourceCulture);
        }
    }
    }
}
