<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(UDTTargetFramework)</TargetFramework>
    <RootNamespace>SensorInventoryDump</RootNamespace>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UniversalDeviceToolkit.Lib\UniversalDeviceToolkit.Lib.csproj" />
  </ItemGroup>

</Project>
