//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalDeviceToolkit.Plugins.ShellIntegration.Resources
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("Codex.ResourceGenerator", "1.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class Resource
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resource()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource", typeof(Resource).Assembly);
                }

                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PluginName.
    /// </summary>
    public static string PluginName {
        get {
            return ResourceManager.GetString("PluginName", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PluginDescription.
    /// </summary>
    public static string PluginDescription {
        get {
            return ResourceManager.GetString("PluginDescription", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.SettingsPageTitle.
    /// </summary>
    public static string SettingsPageTitle {
        get {
            return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.Subtitle.
    /// </summary>
    public static string Subtitle {
        get {
            return ResourceManager.GetString("Subtitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.EnableButton.
    /// </summary>
    public static string EnableButton {
        get {
            return ResourceManager.GetString("EnableButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.DisableButton.
    /// </summary>
    public static string DisableButton {
        get {
            return ResourceManager.GetString("DisableButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.OpenStyleSettingsButton.
    /// </summary>
    public static string OpenStyleSettingsButton {
        get {
            return ResourceManager.GetString("OpenStyleSettingsButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.OpenStyleShortButton.
    /// </summary>
    public static string OpenStyleShortButton {
        get {
            return ResourceManager.GetString("OpenStyleShortButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.RefreshButton.
    /// </summary>
    public static string RefreshButton {
        get {
            return ResourceManager.GetString("RefreshButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ResetButton.
    /// </summary>
    public static string ResetButton {
        get {
            return ResourceManager.GetString("ResetButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ApplyButton.
    /// </summary>
    public static string ApplyButton {
        get {
            return ResourceManager.GetString("ApplyButton", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.OptimizationHint.
    /// </summary>
    public static string OptimizationHint {
        get {
            return ResourceManager.GetString("OptimizationHint", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusDetected.
    /// </summary>
    public static string StatusDetected {
        get {
            return ResourceManager.GetString("StatusDetected", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusNotDetected.
    /// </summary>
    public static string StatusNotDetected {
        get {
            return ResourceManager.GetString("StatusNotDetected", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusRegistered.
    /// </summary>
    public static string StatusRegistered {
        get {
            return ResourceManager.GetString("StatusRegistered", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusUnregistered.
    /// </summary>
    public static string StatusUnregistered {
        get {
            return ResourceManager.GetString("StatusUnregistered", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusDetailDefault.
    /// </summary>
    public static string StatusDetailDefault {
        get {
            return ResourceManager.GetString("StatusDetailDefault", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusEnabledBadge.
    /// </summary>
    public static string StatusEnabledBadge {
        get {
            return ResourceManager.GetString("StatusEnabledBadge", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusDisabledBadge.
    /// </summary>
    public static string StatusDisabledBadge {
        get {
            return ResourceManager.GetString("StatusDisabledBadge", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusMissingBadge.
    /// </summary>
    public static string StatusMissingBadge {
        get {
            return ResourceManager.GetString("StatusMissingBadge", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusUnknownBadge.
    /// </summary>
    public static string StatusUnknownBadge {
        get {
            return ResourceManager.GetString("StatusUnknownBadge", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PathLabel.
    /// </summary>
    public static string PathLabel {
        get {
            return ResourceManager.GetString("PathLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.NotFound.
    /// </summary>
    public static string NotFound {
        get {
            return ResourceManager.GetString("NotFound", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ManagedConfigLabel.
    /// </summary>
    public static string ManagedConfigLabel {
        get {
            return ResourceManager.GetString("ManagedConfigLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ManagedConfigNotReady.
    /// </summary>
    public static string ManagedConfigNotReady {
        get {
            return ResourceManager.GetString("ManagedConfigNotReady", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusEnableCompleted.
    /// </summary>
    public static string StatusEnableCompleted {
        get {
            return ResourceManager.GetString("StatusEnableCompleted", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusEnableFailed.
    /// </summary>
    public static string StatusEnableFailed {
        get {
            return ResourceManager.GetString("StatusEnableFailed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusDisableCompleted.
    /// </summary>
    public static string StatusDisableCompleted {
        get {
            return ResourceManager.GetString("StatusDisableCompleted", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusDisableFailed.
    /// </summary>
    public static string StatusDisableFailed {
        get {
            return ResourceManager.GetString("StatusDisableFailed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.StatusOpenedStyleSettings.
    /// </summary>
    public static string StatusOpenedStyleSettings {
        get {
            return ResourceManager.GetString("StatusOpenedStyleSettings", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ProfileSavedShellMissing.
    /// </summary>
    public static string ProfileSavedShellMissing {
        get {
            return ResourceManager.GetString("ProfileSavedShellMissing", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ApplyCompletedEnabled.
    /// </summary>
    public static string ApplyCompletedEnabled {
        get {
            return ResourceManager.GetString("ApplyCompletedEnabled", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ApplyCompletedDisabled.
    /// </summary>
    public static string ApplyCompletedDisabled {
        get {
            return ResourceManager.GetString("ApplyCompletedDisabled", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.FallbackLoadError.
    /// </summary>
    public static string FallbackLoadError {
        get {
            return ResourceManager.GetString("FallbackLoadError", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.AppearanceSection.
    /// </summary>
    public static string AppearanceSection {
        get {
            return ResourceManager.GetString("AppearanceSection", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.AppearanceSectionHint.
    /// </summary>
    public static string AppearanceSectionHint {
        get {
            return ResourceManager.GetString("AppearanceSectionHint", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PaletteSection.
    /// </summary>
    public static string PaletteSection {
        get {
            return ResourceManager.GetString("PaletteSection", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PaletteSectionHint.
    /// </summary>
    public static string PaletteSectionHint {
        get {
            return ResourceManager.GetString("PaletteSectionHint", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PreviewSection.
    /// </summary>
    public static string PreviewSection {
        get {
            return ResourceManager.GetString("PreviewSection", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PreviewHint.
    /// </summary>
    public static string PreviewHint {
        get {
            return ResourceManager.GetString("PreviewHint", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PathsSection.
    /// </summary>
    public static string PathsSection {
        get {
            return ResourceManager.GetString("PathsSection", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.MotionToggleLabel.
    /// </summary>
    public static string MotionToggleLabel {
        get {
            return ResourceManager.GetString("MotionToggleLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ShadowToggleLabel.
    /// </summary>
    public static string ShadowToggleLabel {
        get {
            return ResourceManager.GetString("ShadowToggleLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ColorSchemeLabel.
    /// </summary>
    public static string ColorSchemeLabel {
        get {
            return ResourceManager.GetString("ColorSchemeLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ColorSchemeAuto.
    /// </summary>
    public static string ColorSchemeAuto {
        get {
            return ResourceManager.GetString("ColorSchemeAuto", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ColorSchemeLight.
    /// </summary>
    public static string ColorSchemeLight {
        get {
            return ResourceManager.GetString("ColorSchemeLight", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ColorSchemeDark.
    /// </summary>
    public static string ColorSchemeDark {
        get {
            return ResourceManager.GetString("ColorSchemeDark", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.VisualEffectLabel.
    /// </summary>
    public static string VisualEffectLabel {
        get {
            return ResourceManager.GetString("VisualEffectLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.EffectNone.
    /// </summary>
    public static string EffectNone {
        get {
            return ResourceManager.GetString("EffectNone", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.EffectTransparent.
    /// </summary>
    public static string EffectTransparent {
        get {
            return ResourceManager.GetString("EffectTransparent", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.EffectBlur.
    /// </summary>
    public static string EffectBlur {
        get {
            return ResourceManager.GetString("EffectBlur", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.EffectAcrylic.
    /// </summary>
    public static string EffectAcrylic {
        get {
            return ResourceManager.GetString("EffectAcrylic", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ShowDelayLabel.
    /// </summary>
    public static string ShowDelayLabel {
        get {
            return ResourceManager.GetString("ShowDelayLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ShowDelayValueFormat.
    /// </summary>
    public static string ShowDelayValueFormat {
        get {
            return ResourceManager.GetString("ShowDelayValueFormat", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ShadowStrengthLabel.
    /// </summary>
    public static string ShadowStrengthLabel {
        get {
            return ResourceManager.GetString("ShadowStrengthLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.ShadowStrengthValueFormat.
    /// </summary>
    public static string ShadowStrengthValueFormat {
        get {
            return ResourceManager.GetString("ShadowStrengthValueFormat", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.AccentColorLabel.
    /// </summary>
    public static string AccentColorLabel {
        get {
            return ResourceManager.GetString("AccentColorLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.BackgroundColorLabel.
    /// </summary>
    public static string BackgroundColorLabel {
        get {
            return ResourceManager.GetString("BackgroundColorLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.HoverColorLabel.
    /// </summary>
    public static string HoverColorLabel {
        get {
            return ResourceManager.GetString("HoverColorLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.TextColorLabel.
    /// </summary>
    public static string TextColorLabel {
        get {
            return ResourceManager.GetString("TextColorLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.MutedColorLabel.
    /// </summary>
    public static string MutedColorLabel {
        get {
            return ResourceManager.GetString("MutedColorLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.TintColorLabel.
    /// </summary>
    public static string TintColorLabel {
        get {
            return ResourceManager.GetString("TintColorLabel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PreviewPrimary.
    /// </summary>
    public static string PreviewPrimary {
        get {
            return ResourceManager.GetString("PreviewPrimary", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PreviewPrimaryHint.
    /// </summary>
    public static string PreviewPrimaryHint {
        get {
            return ResourceManager.GetString("PreviewPrimaryHint", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PreviewSecondary.
    /// </summary>
    public static string PreviewSecondary {
        get {
            return ResourceManager.GetString("PreviewSecondary", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PreviewSecondaryHint.
    /// </summary>
    public static string PreviewSecondaryHint {
        get {
            return ResourceManager.GetString("PreviewSecondaryHint", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PreviewTertiary.
    /// </summary>
    public static string PreviewTertiary {
        get {
            return ResourceManager.GetString("PreviewTertiary", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UniversalDeviceToolkit.Plugins.ShellIntegration.Resources.Resource.PreviewTertiaryHint.
    /// </summary>
    public static string PreviewTertiaryHint {
        get {
            return ResourceManager.GetString("PreviewTertiaryHint", resourceCulture);
        }
    }
    }
}
