//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalDeviceToolkit.Lib.Plugins.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalDeviceToolkit.Lib.Plugins.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Circular dependencies detected: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_DependencyResolution_Circular {
            get {
                return ResourceManager.GetString("Plugin_Error_DependencyResolution_Circular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependency resolution error: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_DependencyResolution_Failed {
            get {
                return ResourceManager.GetString("Plugin_Error_DependencyResolution_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not resolve dependencies for: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_DependencyResolution_Unresolved {
            get {
                return ResourceManager.GetString("Plugin_Error_DependencyResolution_Unresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version conflicts detected for: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_DependencyResolution_VersionConflict {
            get {
                return ResourceManager.GetString("Plugin_Error_DependencyResolution_VersionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to deserialize plugin store response. 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Repository_Deserialize {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_Deserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Repository_DownloadFailed {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to fetch plugin store metadata from all known URLs. 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Repository_FetchFailed {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_FetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin {0} requires Universal Device Toolkit {1} or newer. 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Repository_HostIncompatible {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_HostIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin {0} was installed to disk but could not be loaded by the host. 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Repository_NotLoadable {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_NotLoadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zip entry &apos;{0}&apos; attempts path traversal. 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Repository_PathTraversal {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_PathTraversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin ID cannot be null or empty 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Sandbox_InvalidPluginId {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_InvalidPluginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sandbox not found for plugin: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Sandbox_NotFound {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation timed out 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Sandbox_OperationTimeout {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_OperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource limit exceeded 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Sandbox_ResourceLimit {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_ResourceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sandbox violation: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Sandbox_Violation {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_Violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate validation error: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_CertificateError {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_CertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate chain validation failed: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_ChainFailed {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_ChainFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation disabled 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_Disabled {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate expired on {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_Expired {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin file not found: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_FileNotFound {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin is not signed. Allowed per policy. 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_NotSigned_AllowUnsigned {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_NotSigned_AllowUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin is not signed. Signature required per policy. 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_NotSigned_Required {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_NotSigned_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin is not signed. Allowed because it matches a trusted online package hash. 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_NotSigned_TrustedPackage {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_NotSigned_TrustedPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate not valid until {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_NotYetValid {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_NotYetValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate chain validation passed (test certificate allowed) 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_TestCertificate {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_TestCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation error: {0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Error_Signature_ValidationFailed {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_ValidationFailed", resourceCulture);
            }
        }
    }
}
