//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalDeviceToolkit.Lib.Plugins.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalDeviceToolkit.Lib.Plugins.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular dependencies detected: {0}.
        /// </summary>
        public static string Plugin_Error_DependencyResolution_Circular {
            get {
                return ResourceManager.GetString("Plugin_Error_DependencyResolution_Circular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency resolution error: {0}.
        /// </summary>
        public static string Plugin_Error_DependencyResolution_Failed {
            get {
                return ResourceManager.GetString("Plugin_Error_DependencyResolution_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve dependencies for: {0}.
        /// </summary>
        public static string Plugin_Error_DependencyResolution_Unresolved {
            get {
                return ResourceManager.GetString("Plugin_Error_DependencyResolution_Unresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version conflicts detected for: {0}.
        /// </summary>
        public static string Plugin_Error_DependencyResolution_VersionConflict {
            get {
                return ResourceManager.GetString("Plugin_Error_DependencyResolution_VersionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize plugin store response..
        /// </summary>
        public static string Plugin_Error_Repository_Deserialize {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_Deserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download {0}.
        /// </summary>
        public static string Plugin_Error_Repository_DownloadFailed {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch plugin store metadata from all known URLs..
        /// </summary>
        public static string Plugin_Error_Repository_FetchFailed {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_FetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} requires Universal Device Toolkit {1} or newer..
        /// </summary>
        public static string Plugin_Error_Repository_HostIncompatible {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_HostIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} was installed to disk but could not be loaded by the host..
        /// </summary>
        public static string Plugin_Error_Repository_NotLoadable {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_NotLoadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip entry &apos;{0}&apos; attempts path traversal..
        /// </summary>
        public static string Plugin_Error_Repository_PathTraversal {
            get {
                return ResourceManager.GetString("Plugin_Error_Repository_PathTraversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin ID cannot be null or empty.
        /// </summary>
        public static string Plugin_Error_Sandbox_InvalidPluginId {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_InvalidPluginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox not found for plugin: {0}.
        /// </summary>
        public static string Plugin_Error_Sandbox_NotFound {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation timed out.
        /// </summary>
        public static string Plugin_Error_Sandbox_OperationTimeout {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_OperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource limit exceeded.
        /// </summary>
        public static string Plugin_Error_Sandbox_ResourceLimit {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_ResourceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox violation: {0}.
        /// </summary>
        public static string Plugin_Error_Sandbox_Violation {
            get {
                return ResourceManager.GetString("Plugin_Error_Sandbox_Violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate validation error: {0}.
        /// </summary>
        public static string Plugin_Error_Signature_CertificateError {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_CertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate chain validation failed: {0}.
        /// </summary>
        public static string Plugin_Error_Signature_ChainFailed {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_ChainFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation disabled.
        /// </summary>
        public static string Plugin_Error_Signature_Disabled {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate expired on {0}.
        /// </summary>
        public static string Plugin_Error_Signature_Expired {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin file not found: {0}.
        /// </summary>
        public static string Plugin_Error_Signature_FileNotFound {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin is not signed. Allowed per policy..
        /// </summary>
        public static string Plugin_Error_Signature_NotSigned_AllowUnsigned {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_NotSigned_AllowUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin is not signed. Signature required per policy..
        /// </summary>
        public static string Plugin_Error_Signature_NotSigned_Required {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_NotSigned_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin is not signed. Allowed because it matches a trusted online package hash..
        /// </summary>
        public static string Plugin_Error_Signature_NotSigned_TrustedPackage {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_NotSigned_TrustedPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate not valid until {0}.
        /// </summary>
        public static string Plugin_Error_Signature_NotYetValid {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_NotYetValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate chain validation passed (test certificate allowed).
        /// </summary>
        public static string Plugin_Error_Signature_TestCertificate {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_TestCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error: {0}.
        /// </summary>
        public static string Plugin_Error_Signature_ValidationFailed {
            get {
                return ResourceManager.GetString("Plugin_Error_Signature_ValidationFailed", resourceCulture);
            }
        }
    }
}
