# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SSC-STUDIO.LenovoLegionToolkit
PackageVersion: 4.1.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-05-31
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SSC-STUDIO/UniversalDeviceToolkit/releases/download/v4.1.0/LenovoLegionToolkit_v4.1.0_Setup.exe
  InstallerSha256: 585485F697F642930052784B7BC97CE6AB79EA1749C2582E98799110667C399A
ManifestType: installer
ManifestVersion: 1.10.0
