# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SSC-STUDIO.LenovoLegionToolkit
PackageVersion: 4.1.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-05-31
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SSC-STUDIO/UniversalDeviceToolkit/releases/download/v4.1.0/LenovoLegionToolkit_v4.1.0_Setup.exe
  InstallerSha256: 972265682DCB6D4D72706C664DBAE1A85731FAFE7DA3A339241EA063259A936F
ManifestType: installer
ManifestVersion: 1.10.0