<?xml version='1.0' encoding='utf-8'?>
<Project>
  <PropertyGroup>
    <MajorVersion>3</MajorVersion>
    <MinorVersion>7</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <ReleaseVersion>$(MajorVersion).$(MinorVersion).$(PatchVersion)</ReleaseVersion>
    <WindowsVersion>$(ReleaseVersion).0</WindowsVersion>
    <GitCommitHash>unknown</GitCommitHash>

    <Version Condition="'$(Version)' == ''">$(ReleaseVersion)</Version>
    <FileVersion Condition="'$(FileVersion)' == ''">$(WindowsVersion)</FileVersion>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(WindowsVersion)</AssemblyVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <InformationalVersion>$(Version)+$(GitCommitHash)</InformationalVersion>
    <SkipGitInfoLookup>$([System.String]::Copy('$(MSBuildThisFileDirectory)').StartsWith('\\wsl.localhost\', System.StringComparison.OrdinalIgnoreCase))</SkipGitInfoLookup>
    <LLTTargetFramework>net10.0-windows10.0.26100.0</LLTTargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <RestoreConfigFile Condition="'$(RestoreConfigFile)' == '' and Exists('$(MSBuildThisFileDirectory)NuGet.Config')">$(MSBuildThisFileDirectory)NuGet.Config</RestoreConfigFile>
  </PropertyGroup>

  <Target Name="GetGitInfo" BeforeTargets="BeforeBuild">
    <Exec Command="git rev-parse --short HEAD" ConsoleToMSBuild="true" IgnoreExitCode="true" WorkingDirectory="$(MSBuildThisFileDirectory)" Condition="'$(SkipGitInfoLookup)' != 'True'">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitCommitHashRaw" />
    </Exec>

    <PropertyGroup>
      <GitCommitHashRaw>$([System.String]::new($(GitCommitHashRaw)).Trim())</GitCommitHashRaw>
    </PropertyGroup>

    <PropertyGroup>
      <GitCommitHash Condition=" '$(GitCommitHashRaw)' != '' ">$(GitCommitHashRaw)</GitCommitHash>
      <InformationalVersion>$(Version)+$(GitCommitHash)</InformationalVersion>
    </PropertyGroup>
  </Target>
</Project>
