$resxPath = "LenovoLegionToolkit.WPF\Resources\Resource.resx"
$outputPath = "LenovoLegionToolkit.WPF\Resources\Resource.Designer.cs"

Write-Host "Reading Resource.resx..."
[xml]$xml = Get-Content $resxPath -Encoding UTF8
$resources = $xml.root.data | Where-Object { $_.name -and -not $_.type } | Sort-Object { $_.name }

Write-Host "Found $($resources.Count) resources. Generating Resource.Designer.cs..."

$sb = New-Object System.Text.StringBuilder

# Header
$sb.AppendLine("//------------------------------------------------------------------------------") | Out-Null
$sb.AppendLine("// <auto-generated>") | Out-Null
$sb.AppendLine("//     This code was generated by a tool.") | Out-Null
$sb.AppendLine("//     Runtime Version:4.0.30319.42000") | Out-Null
$sb.AppendLine("//") | Out-Null
$sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if") | Out-Null
$sb.AppendLine("//     the code is regenerated.") | Out-Null
$sb.AppendLine("// </auto-generated>") | Out-Null
$sb.AppendLine("//------------------------------------------------------------------------------") | Out-Null
$sb.AppendLine("") | Out-Null
$sb.AppendLine("namespace LenovoLegionToolkit.WPF.Resources {") | Out-Null
$sb.AppendLine("    using System;") | Out-Null
$sb.AppendLine("    ") | Out-Null
$sb.AppendLine("    ") | Out-Null
$sb.AppendLine("    /// <summary>") | Out-Null
$sb.AppendLine("    ///   A strongly-typed resource class, for looking up localized strings, etc.") | Out-Null
$sb.AppendLine("    /// </summary>") | Out-Null
$sb.AppendLine("    // This class was auto-generated by the StronglyTypedResourceBuilder") | Out-Null
$sb.AppendLine("    // class via a tool like ResGen or Visual Studio.") | Out-Null
$sb.AppendLine("    // To add or remove a member, edit your .ResX file then rerun ResGen") | Out-Null
$sb.AppendLine("    // with the /str option, or rebuild your VS project.") | Out-Null
$sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(`"System.Resources.Tools.StronglyTypedResourceBuilder`", `"17.0.0.0`")]") | Out-Null
$sb.AppendLine("    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]") | Out-Null
$sb.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]") | Out-Null
$sb.AppendLine("    public class Resource {") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        private static global::System.Resources.ResourceManager resourceMan;") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        private static global::System.Globalization.CultureInfo resourceCulture;") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(`"Microsoft.Performance`", `"CA1811:AvoidUncalledPrivateCode`")]") | Out-Null
$sb.AppendLine("        internal Resource() {") | Out-Null
$sb.AppendLine("        }") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        /// <summary>") | Out-Null
$sb.AppendLine("        ///   Returns the cached ResourceManager instance used by this class.") | Out-Null
$sb.AppendLine("        /// </summary>") | Out-Null
$sb.AppendLine("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]") | Out-Null
$sb.AppendLine("        public static global::System.Resources.ResourceManager ResourceManager {") | Out-Null
$sb.AppendLine("            get {") | Out-Null
$sb.AppendLine("                if (object.ReferenceEquals(resourceMan, null)) {") | Out-Null
$sb.AppendLine("                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(`"LenovoLegionToolkit.WPF.Resources.Resource`", typeof(Resource).Assembly);") | Out-Null
$sb.AppendLine("                    resourceMan = temp;") | Out-Null
$sb.AppendLine("                }") | Out-Null
$sb.AppendLine("                return resourceMan;") | Out-Null
$sb.AppendLine("            }") | Out-Null
$sb.AppendLine("        }") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        /// <summary>") | Out-Null
$sb.AppendLine("        ///   Overrides the current thread's CurrentUICulture property for all") | Out-Null
$sb.AppendLine("        ///   resource lookups using this strongly typed resource class.") | Out-Null
$sb.AppendLine("        /// </summary>") | Out-Null
$sb.AppendLine("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]") | Out-Null
$sb.AppendLine("        public static global::System.Globalization.CultureInfo Culture {") | Out-Null
$sb.AppendLine("            get {") | Out-Null
$sb.AppendLine("                return resourceCulture;") | Out-Null
$sb.AppendLine("            }") | Out-Null
$sb.AppendLine("            set {") | Out-Null
$sb.AppendLine("                resourceCulture = value;") | Out-Null
$sb.AppendLine("            }") | Out-Null
$sb.AppendLine("        }") | Out-Null

# Generate properties for each resource
$count = 0
foreach ($resource in $resources) {
    $name = $resource.name
    $valueNode = $resource.SelectSingleNode("value")
    $value = if ($valueNode) { $valueNode.InnerText } else { "" }
    $description = ""
    if ($value) {
        $description = $value -replace "`r`n", " " -replace "`n", " " -replace "`r", " "
        if ($description.Length -gt 50) {
            $description = $description.Substring(0, 50) + "..."
        }
        $description = $description -replace '"', '&quot;'
    }
    
    $sb.AppendLine("        ") | Out-Null
    $sb.AppendLine("        /// <summary>") | Out-Null
    if ($description) {
        $sb.AppendLine("        ///   Looks up a localized string similar to $description.") | Out-Null
    } else {
        $sb.AppendLine("        ///   Looks up a localized string.") | Out-Null
    }
    $sb.AppendLine("        /// </summary>") | Out-Null
    $sb.AppendLine("        public static string $name {") | Out-Null
    $sb.AppendLine("            get {") | Out-Null
    $sb.AppendLine("                return ResourceManager.GetString(`"$name`", resourceCulture);") | Out-Null
    $sb.AppendLine("            }") | Out-Null
    $sb.AppendLine("        }") | Out-Null
    
    $count++
    if ($count % 100 -eq 0) {
        Write-Host "Generated $count properties..."
    }
}

$sb.AppendLine("    }") | Out-Null
$sb.AppendLine("}") | Out-Null

# Write to file
$content = $sb.ToString()
[System.IO.File]::WriteAllText((Resolve-Path $outputPath -ErrorAction SilentlyContinue) -or (Join-Path (Get-Location) $outputPath), $content, [System.Text.Encoding]::UTF8)
Write-Host "Successfully generated Resource.Designer.cs with $count resource properties"
