<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <AssemblyName>UniversalDeviceToolkit.Plugins.Shared.Core</AssemblyName>
    <RootNamespace>UniversalDeviceToolkit.Plugins.Core</RootNamespace>
    <IsPluginSdkProject>True</IsPluginSdkProject>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
