<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(UDTTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableUdtTestHooks>true</EnableUdtTestHooks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UniversalDeviceToolkit.CLI.Lib\UniversalDeviceToolkit.CLI.Lib.csproj" />
  </ItemGroup>

</Project>
