//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugins.CustomMouse.Resources
{
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("Codex.ResourceGenerator", "1.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class Resource
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resource()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("LenovoLegionToolkit.Plugins.CustomMouse.Resources.Resource", typeof(Resource).Assembly);
                }

                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }

        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }

        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }

        public static string FeatureSubtitle {
            get {
                return ResourceManager.GetString("FeatureSubtitle", resourceCulture);
            }
        }

        public static string PollingRateLabel {
            get {
                return ResourceManager.GetString("PollingRateLabel", resourceCulture);
            }
        }

        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }

        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }

        public static string StatusResetDefaults {
            get {
                return ResourceManager.GetString("StatusResetDefaults", resourceCulture);
            }
        }

        public static string StatusInvalidDpi {
            get {
                return ResourceManager.GetString("StatusInvalidDpi", resourceCulture);
            }
        }

        public static string StatusSelectValidPolling {
            get {
                return ResourceManager.GetString("StatusSelectValidPolling", resourceCulture);
            }
        }

        public static string StatusInvalidPolling {
            get {
                return ResourceManager.GetString("StatusInvalidPolling", resourceCulture);
            }
        }

        public static string StatusProfileSaved {
            get {
                return ResourceManager.GetString("StatusProfileSaved", resourceCulture);
            }
        }

        public static string SettingsSubtitle {
            get {
                return ResourceManager.GetString("SettingsSubtitle", resourceCulture);
            }
        }

        public static string PointerSpeedLabel {
            get {
                return ResourceManager.GetString("PointerSpeedLabel", resourceCulture);
            }
        }

        public static string SwapButtonsLabel {
            get {
                return ResourceManager.GetString("SwapButtonsLabel", resourceCulture);
            }
        }

        public static string AutoThemeLabel {
            get {
                return ResourceManager.GetString("AutoThemeLabel", resourceCulture);
            }
        }

        public static string CursorHint {
            get {
                return ResourceManager.GetString("CursorHint", resourceCulture);
            }
        }

        public static string ApplyToWindowsButton {
            get {
                return ResourceManager.GetString("ApplyToWindowsButton", resourceCulture);
            }
        }

        public static string ApplyCursorThemeNowButton {
            get {
                return ResourceManager.GetString("ApplyCursorThemeNowButton", resourceCulture);
            }
        }

        public static string ReloadButton {
            get {
                return ResourceManager.GetString("ReloadButton", resourceCulture);
            }
        }

        public static string StatusApplyPointerFail {
            get {
                return ResourceManager.GetString("StatusApplyPointerFail", resourceCulture);
            }
        }

        public static string StatusApplySwapFail {
            get {
                return ResourceManager.GetString("StatusApplySwapFail", resourceCulture);
            }
        }

        public static string StatusWindowsApplied {
            get {
                return ResourceManager.GetString("StatusWindowsApplied", resourceCulture);
            }
        }

        public static string StatusCursorApplyFailed {
            get {
                return ResourceManager.GetString("StatusCursorApplyFailed", resourceCulture);
            }
        }

        public static string StatusReloaded {
            get {
                return ResourceManager.GetString("StatusReloaded", resourceCulture);
            }
        }

        public static string CursorAppliedUnknownTheme {
            get {
                return ResourceManager.GetString("CursorAppliedUnknownTheme", resourceCulture);
            }
        }

        public static string CursorAppliedFormat {
            get {
                return ResourceManager.GetString("CursorAppliedFormat", resourceCulture);
            }
        }

        public static string DpiLabel {
            get {
                return ResourceManager.GetString("DpiLabel", resourceCulture);
            }
        }
    }
}
