<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPluginToolProject>true</IsPluginToolProject>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
