# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SSC-STUDIO.LenovoLegionToolkit
PackageVersion: 4.2.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-06-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SSC-STUDIO/UniversalDeviceToolkit/releases/download/v4.2.0/LenovoLegionToolkit_v4.2.0_Setup.exe
  InstallerSha256: D2090BC29F1B81BAB63F51BE65BB2F5FF369EC103919EB06D6E2FBA34749043F
ManifestType: installer
ManifestVersion: 1.10.0