<?xml version='1.0' encoding='utf-8'?>
<Project>
  

  <PropertyGroup>
    <IsPluginTestProject>$([System.String]::Copy('$(MSBuildProjectName)').EndsWith('.Tests'))</IsPluginTestProject>
    <IsPluginToolProject Condition="'$(IsPluginToolProject)' == ''">False</IsPluginToolProject>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'LenovoLegionToolkit.Plugins.SDK' AND '$(IsPluginTestProject)' != 'True' AND '$(IsPluginToolProject)' != 'True'">
    <Version>1.0.5</Version>
    <FileVersion>1.0.5</FileVersion>
    <AssemblyVersion>1.0.5</AssemblyVersion>
    <InformationalVersion>1.0.5</InformationalVersion>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(UseWPF)' == 'true' AND '$(MSBuildProjectName)' != 'LenovoLegionToolkit.Plugins.SDK' AND '$(IsPluginToolProject)' != 'True'">
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'LenovoLegionToolkit.Plugins.SDK'">
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'LenovoLegionToolkit.Plugins.SDK' AND '$(IsPluginTestProject)' != 'True' AND '$(IsPluginToolProject)' != 'True'">
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'LenovoLegionToolkit.Plugins.SDK' AND '$(IsPluginTestProject)' != 'True' AND '$(IsPluginToolProject)' != 'True'">
    <Copyright>© 2025 Lenovo Legion Toolkit Contributors</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
    <Authors>Lenovo Legion Toolkit Contributors</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(UseWPF)' == 'true' AND '$(IsPluginToolProject)' != 'True'">
    <UseCommonControls>true</UseCommonControls>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'LenovoLegionToolkit.Plugins.SDK' AND '$(IsPluginTestProject)' != 'True' AND '$(IsPluginToolProject)' != 'True'">
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  
  <PropertyGroup>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(UseWPF)' == 'true' AND '$(IsPluginToolProject)' != 'True'">
    <SatelliteResourceLanguages>zh-hans;zh-hant;ja;ko;de</SatelliteResourceLanguages>
  </PropertyGroup>

  
  <ItemGroup>
    <PackageReference Update="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Update="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'LenovoLegionToolkit.Plugins.SDK' AND '$(IsPluginTestProject)' != 'True' AND '$(IsPluginToolProject)' != 'True'">
    <Reference Include="LenovoLegionToolkit.Lib">
      <HintPath>$(MSBuildThisFileDirectory)Dependencies\Host\LenovoLegionToolkit.Lib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  
  <ItemGroup Condition="'$(UseWPF)' == 'true' AND '$(MSBuildProjectName)' != 'LenovoLegionToolkit.Plugins.SDK' AND '$(IsPluginTestProject)' != 'True' AND '$(IsPluginToolProject)' != 'True'">
    <PackageReference Include="WPF-UI" Version="2.1.0" />
  </ItemGroup>

  
  <Target Name="CleanupPluginOutput" AfterTargets="Build" Condition="'$(MSBuildProjectName)' != 'LenovoLegionToolkit.Plugins.SDK' AND '$(IsPluginTestProject)' != 'True' AND '$(IsPluginToolProject)' != 'True'">
    <ItemGroup>
      <FilesToDelete Include="$(OutputPath)*.deps.json" />
      <FilesToDelete Include="$(OutputPath)*.runtimeconfig.json" />
      <FilesToDelete Include="$(OutputPath)Lenovo Legion Toolkit.*" />
      <FilesToDelete Include="$(OutputPath)LenovoLegionToolkit.WPF.*" />
      <FilesToDelete Include="$(OutputPath)LenovoLegionToolkit.Lib.*" />
      <FilesToDelete Include="$(OutputPath)LenovoLegionToolkit.Lib.Macro.*" />
      <FilesToDelete Include="$(OutputPath)LenovoLegionToolkit.Lib.Automation.*" />
      <FilesToDelete Include="$(OutputPath)LenovoLegionToolkit.CLI.Lib.*" />
      <FilesToDelete Include="$(OutputPath)LenovoLegionToolkit.Plugins.SDK.*" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" ContinueOnError="true" />
    <RemoveDir Directories="$(OutputPath)\tools" ContinueOnError="true" />
  </Target>

</Project>