//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalDeviceToolkit.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalDeviceToolkit.Lib.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string AccentColorSource_Custom {
            get {
                return ResourceManager.GetString("AccentColorSource_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string AccentColorSource_System {
            get {
                return ResourceManager.GetString("AccentColorSource_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_Off {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On, always 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_OnAlways {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On, when sleeping 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_OnWhenSleeping {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnWhenSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile will not apply without AC adapter (Full wattage) connected. 的本地化字符串。
        /// </summary>
        public static string AmdOverclocking_Ac_Message {
            get {
                return ResourceManager.GetString("AmdOverclocking_Ac_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not initialized. 的本地化字符串。
        /// </summary>
        public static string AmdOverclocking_Not_Initialized_Message {
            get {
                return ResourceManager.GetString("AmdOverclocking_Not_Initialized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not supported. 的本地化字符串。
        /// </summary>
        public static string AmdOverclocking_Not_Supported {
            get {
                return ResourceManager.GetString("AmdOverclocking_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string AutorunState_Disabled {
            get {
                return ResourceManager.GetString("AutorunState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string AutorunState_Enabled {
            get {
                return ResourceManager.GetString("AutorunState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled, delayed 的本地化字符串。
        /// </summary>
        public static string AutorunState_EnabledDelayed {
            get {
                return ResourceManager.GetString("AutorunState_EnabledDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string BatteryNightChargeState_Off {
            get {
                return ResourceManager.GetString("BatteryNightChargeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string BatteryNightChargeState_On {
            get {
                return ResourceManager.GetString("BatteryNightChargeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conservation 的本地化字符串。
        /// </summary>
        public static string BatteryState_Conservation {
            get {
                return ResourceManager.GetString("BatteryState_Conservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string BatteryState_Normal {
            get {
                return ResourceManager.GetString("BatteryState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rapid Charge 的本地化字符串。
        /// </summary>
        public static string BatteryState_RapidCharge {
            get {
                return ResourceManager.GetString("BatteryState_RapidCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Fan 的本地化字符串。
        /// </summary>
        public static string CustomFanCurveControl_Fan_CPU {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Fan 的本地化字符串。
        /// </summary>
        public static string CustomFanCurveControl_Fan_GPU {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Fan 的本地化字符串。
        /// </summary>
        public static string CustomFanCurveControl_Fan_System {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}% 的本地化字符串。
        /// </summary>
        public static string DpiScale_DisplayName_Format {
            get {
                return ResourceManager.GetString("DpiScale_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness must be between 0 and 9 的本地化字符串。
        /// </summary>
        public static string Exception_BrightnessRange {
            get {
                return ResourceManager.GetString("Exception_BrightnessRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built in display not found 的本地化字符串。
        /// </summary>
        public static string Exception_BuiltInDisplayNotFound {
            get {
                return ResourceManager.GetString("Exception_BuiltInDisplayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read variable {0} from UEFI 的本地化字符串。
        /// </summary>
        public static string Exception_CannotReadVariableUEFI {
            get {
                return ResourceManager.GetString("Exception_CannotReadVariableUEFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set UEFI privileges 的本地化字符串。
        /// </summary>
        public static string Exception_CannotSetUEFIPrivileges {
            get {
                return ResourceManager.GetString("Exception_CannotSetUEFIPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write variable {0} to UEFI 的本地化字符串。
        /// </summary>
        public static string Exception_CannotWriteVariableUEFI {
            get {
                return ResourceManager.GetString("Exception_CannotWriteVariableUEFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t manage RGB keyboard with Vantage enabled 的本地化字符串。
        /// </summary>
        public static string Exception_CantManageWithVantage {
            get {
                return ResourceManager.GetString("Exception_CantManageWithVantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command cannot be null or empty. 的本地化字符串。
        /// </summary>
        public static string Exception_CommandCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_CommandCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command &apos;{0}&apos; failed with exit code {1}. {2} 的本地化字符串。
        /// </summary>
        public static string Exception_CommandExitedNonZero {
            get {
                return ResourceManager.GetString("Exception_CommandExitedNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command failed security validation: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_CommandFailedSecurity {
            get {
                return ResourceManager.GetString("Exception_CommandFailedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t deserialize effects 的本地化字符串。
        /// </summary>
        public static string Exception_CouldNotDeserializeEffects {
            get {
                return ResourceManager.GetString("Exception_CouldNotDeserializeEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t get color &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string Exception_CouldNotGetColor {
            get {
                return ResourceManager.GetString("Exception_CouldNotGetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t read the {0} setting 的本地化字符串。
        /// </summary>
        public static string Exception_CouldNotReadRegistrySetting {
            get {
                return ResourceManager.GetString("Exception_CouldNotReadRegistrySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current process file name cannot be null 的本地化字符串。
        /// </summary>
        public static string Exception_CurrentProcessFileNameNull {
            get {
                return ResourceManager.GetString("Exception_CurrentProcessFileNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current process file version cannot be null 的本地化字符串。
        /// </summary>
        public static string Exception_CurrentProcessFileVersionNull {
            get {
                return ResourceManager.GetString("Exception_CurrentProcessFileVersionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current user value is null 的本地化字符串。
        /// </summary>
        public static string Exception_CurrentUserValueNull {
            get {
                return ResourceManager.GetString("Exception_CurrentUserValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments contain dangerous characters 的本地化字符串。
        /// </summary>
        public static string Exception_DangerousArguments {
            get {
                return ResourceManager.GetString("Exception_DangerousArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dangerous pattern detected in arguments for {0} 的本地化字符串。
        /// </summary>
        public static string Exception_DangerousPatternInArgs {
            get {
                return ResourceManager.GetString("Exception_DangerousPatternInArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletion of critical registry keys is not allowed 的本地化字符串。
        /// </summary>
        public static string Exception_DeletionCriticalRegistryNotAllowed {
            get {
                return ResourceManager.GetString("Exception_DeletionCriticalRegistryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletion of system paths is not allowed 的本地化字符串。
        /// </summary>
        public static string Exception_DeletionSystemPathsNotAllowed {
            get {
                return ResourceManager.GetString("Exception_DeletionSystemPathsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device handle is not available 的本地化字符串。
        /// </summary>
        public static string Exception_DeviceHandleNotAvailable {
            get {
                return ResourceManager.GetString("Exception_DeviceHandleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceIoControl returned 0, last error: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_DeviceIoControlError {
            get {
                return ResourceManager.GetString("Exception_DeviceIoControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceIoControl failed with error: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_DeviceIoControlErrorWithCode {
            get {
                return ResourceManager.GetString("Exception_DeviceIoControlErrorWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack id mismatch. Expected &apos;{0}&apos;, got &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackIdMismatch {
            get {
                return ResourceManager.GetString("Exception_DevicePackIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack &apos;{0}&apos; manifest is empty. 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackManifestEmpty {
            get {
                return ResourceManager.GetString("Exception_DevicePackManifestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack &apos;{0}&apos; does not contain {1}. 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackNoManifest {
            get {
                return ResourceManager.GetString("Exception_DevicePackNoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack &apos;{0}&apos; is not available in the online resource catalog. 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackNotAvailable {
            get {
                return ResourceManager.GetString("Exception_DevicePackNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack &apos;{0}&apos; is missing SHA256 metadata. 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackSha256Missing {
            get {
                return ResourceManager.GetString("Exception_DevicePackSha256Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack contains an unsafe path: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackUnsafePath {
            get {
                return ResourceManager.GetString("Exception_DevicePackUnsafePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack contains unsupported file type: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackUnsupportedFileType {
            get {
                return ResourceManager.GetString("Exception_DevicePackUnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack &apos;{0}&apos; has an empty download URL. 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackUrlEmpty {
            get {
                return ResourceManager.GetString("Exception_DevicePackUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack vendor mismatch. Expected &apos;{0}&apos;, got &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackVendorMismatch {
            get {
                return ResourceManager.GetString("Exception_DevicePackVendorMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device pack contains a Windows-style path separator: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePackWindowsPathSep {
            get {
                return ResourceManager.GetString("Exception_DevicePackWindowsPathSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device property is not a GUID 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePropertyNotGUID {
            get {
                return ResourceManager.GetString("Exception_DevicePropertyNotGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device property is not a string 的本地化字符串。
        /// </summary>
        public static string Exception_DevicePropertyNotString {
            get {
                return ResourceManager.GetString("Exception_DevicePropertyNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error sending driver command: controlCode={0} 的本地化字符串。
        /// </summary>
        public static string Exception_DriverCommandError {
            get {
                return ResourceManager.GetString("Exception_DriverCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error getting driver handle: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_DriverHandleError {
            get {
                return ResourceManager.GetString("Exception_DriverHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get handle for driver: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_DriverHandleFailed {
            get {
                return ResourceManager.GetString("Exception_DriverHandleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explorer did not exit in time. 的本地化字符串。
        /// </summary>
        public static string Exception_ExplorerDidNotExit {
            get {
                return ResourceManager.GetString("Exception_ExplorerDidNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explorer did not restart in time. 的本地化字符串。
        /// </summary>
        public static string Exception_ExplorerDidNotRestart {
            get {
                return ResourceManager.GetString("Exception_ExplorerDidNotRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to deserialize JSON 的本地化字符串。
        /// </summary>
        public static string Exception_FailedToDeserializeJSON {
            get {
                return ResourceManager.GetString("Exception_FailedToDeserializeJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to deserialize profile. 的本地化字符串。
        /// </summary>
        public static string Exception_FailedToDeserializeProfile {
            get {
                return ResourceManager.GetString("Exception_FailedToDeserializeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to register changes on task {0} in {1} [type={2}] 的本地化字符串。
        /// </summary>
        public static string Exception_FailedToRegisterTask {
            get {
                return ResourceManager.GetString("Exception_FailedToRegisterTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start Explorer. 的本地化字符串。
        /// </summary>
        public static string Exception_FailedToStartExplorer {
            get {
                return ResourceManager.GetString("Exception_FailedToStartExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to verify {0} state was set to {1}. 的本地化字符串。
        /// </summary>
        public static string Exception_FailedVerifyState {
            get {
                return ResourceManager.GetString("Exception_FailedVerifyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan table length must be 10 的本地化字符串。
        /// </summary>
        public static string Exception_FanTableLength {
            get {
                return ResourceManager.GetString("Exception_FanTableLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File checksum mismatch 的本地化字符串。
        /// </summary>
        public static string Exception_FileChecksumMismatch {
            get {
                return ResourceManager.GetString("Exception_FileChecksumMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset with ID {0} not found 的本地化字符串。
        /// </summary>
        public static string Exception_GodModePresetNotFound {
            get {
                return ResourceManager.GetString("Exception_GodModePresetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 handle is invalid 的本地化字符串。
        /// </summary>
        public static string Exception_HandleInvalid {
            get {
                return ResourceManager.GetString("Exception_HandleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has to be readable 的本地化字符串。
        /// </summary>
        public static string Exception_HasToBeReadable {
            get {
                return ResourceManager.GetString("Exception_HasToBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has to be writable 的本地化字符串。
        /// </summary>
        public static string Exception_HasToBeWritable {
            get {
                return ResourceManager.GetString("Exception_HasToBeWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interactive shell executables require arguments when waiting for exit 的本地化字符串。
        /// </summary>
        public static string Exception_InteractiveShellRequiresArgs {
            get {
                return ResourceManager.GetString("Exception_InteractiveShellRequiresArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid action key 的本地化字符串。
        /// </summary>
        public static string Exception_InvalidActionKey {
            get {
                return ResourceManager.GetString("Exception_InvalidActionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid environment variable: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_InvalidEnvVariable {
            get {
                return ResourceManager.GetString("Exception_InvalidEnvVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid environment variable value: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_InvalidEnvVariableValue {
            get {
                return ResourceManager.GetString("Exception_InvalidEnvVariableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid file name 的本地化字符串。
        /// </summary>
        public static string Exception_InvalidFileName {
            get {
                return ResourceManager.GetString("Exception_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid settings filename: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_InvalidSettingsFilename {
            get {
                return ResourceManager.GetString("Exception_InvalidSettingsFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid state 的本地化字符串。
        /// </summary>
        public static string Exception_InvalidState {
            get {
                return ResourceManager.GetString("Exception_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid type of formatted 的本地化字符串。
        /// </summary>
        public static string Exception_InvalidTypeOfFormatted {
            get {
                return ResourceManager.GetString("Exception_InvalidTypeOfFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IoCContainer already initialized 的本地化字符串。
        /// </summary>
        public static string Exception_IoCAlreadyInitialized {
            get {
                return ResourceManager.GetString("Exception_IoCAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IoCContainer must be initialized first [type={0}] 的本地化字符串。
        /// </summary>
        public static string Exception_IoCMustBeInitialized {
            get {
                return ResourceManager.GetString("Exception_IoCMustBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key {0} could not be opened 的本地化字符串。
        /// </summary>
        public static string Exception_KeyCouldNotBeOpened {
            get {
                return ResourceManager.GetString("Exception_KeyCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Module cannot be null 的本地化字符串。
        /// </summary>
        public static string Exception_MainModuleNull {
            get {
                return ResourceManager.GetString("Exception_MainModuleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No God Mode preset is available. 的本地化字符串。
        /// </summary>
        public static string Exception_NoGodModePresetAvailable {
            get {
                return ResourceManager.GetString("Exception_NoGodModePresetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No God Mode preset could be created. 的本地化字符串。
        /// </summary>
        public static string Exception_NoGodModePresetCreated {
            get {
                return ResourceManager.GetString("Exception_NoGodModePresetCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No supported controller found 的本地化字符串。
        /// </summary>
        public static string Exception_NoSupportedControllerFound {
            get {
                return ResourceManager.GetString("Exception_NoSupportedControllerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No supported feature found 的本地化字符串。
        /// </summary>
        public static string Exception_NoSupportedFeature {
            get {
                return ResourceManager.GetString("Exception_NoSupportedFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No supported version found 的本地化字符串。
        /// </summary>
        public static string Exception_NoSupportedVersionFound {
            get {
                return ResourceManager.GetString("Exception_NoSupportedVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable not in allowlist: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_NotInAllowlist {
            get {
                return ResourceManager.GetString("Exception_NotInAllowlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No updates available 的本地化字符串。
        /// </summary>
        public static string Exception_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("Exception_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset and count exceed array bounds 的本地化字符串。
        /// </summary>
        public static string Exception_OffsetCountExceedArray {
            get {
                return ResourceManager.GetString("Exception_OffsetCountExceedArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Service Error 的本地化字符串。
        /// </summary>
        public static string Exception_OpenServiceError {
            get {
                return ResourceManager.GetString("Exception_OpenServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Service Manager Error 的本地化字符串。
        /// </summary>
        public static string Exception_OpenServiceManagerError {
            get {
                return ResourceManager.GetString("Exception_OpenServiceManagerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimization action not found: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_OptimizationActionNotFound {
            get {
                return ResourceManager.GetString("Exception_OptimizationActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimization action cannot be reverted: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_OptimizationActionRollbackUnavailable {
            get {
                return ResourceManager.GetString("Exception_OptimizationActionRollbackUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power mode switching is not supported on this device. 的本地化字符串。
        /// </summary>
        public static string Exception_PowerModeNotSupported {
            get {
                return ResourceManager.GetString("Exception_PowerModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power mode &apos;{0}&apos; is unavailable without AC adapter. 的本地化字符串。
        /// </summary>
        public static string Exception_PowerModeUnavailableWithoutAC {
            get {
                return ResourceManager.GetString("Exception_PowerModeUnavailableWithoutAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerShell arguments contain dangerous patterns 的本地化字符串。
        /// </summary>
        public static string Exception_PowerShellDangerousArgs {
            get {
                return ResourceManager.GetString("Exception_PowerShellDangerousArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile file not found. 的本地化字符串。
        /// </summary>
        public static string Exception_ProfileFileNotFound {
            get {
                return ResourceManager.GetString("Exception_ProfileFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile must be between 0 and 6 的本地化字符串。
        /// </summary>
        public static string Exception_ProfileRange {
            get {
                return ResourceManager.GetString("Exception_ProfileRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource catalog is empty. 的本地化字符串。
        /// </summary>
        public static string Exception_ResourceCatalogEmpty {
            get {
                return ResourceManager.GetString("Exception_ResourceCatalogEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RGB Keyboard unsupported 的本地化字符串。
        /// </summary>
        public static string Exception_RGBKeyboardUnsupported {
            get {
                return ResourceManager.GetString("Exception_RGBKeyboardUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings path escapes allowed directory: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_SettingsPathEscapesAllowedDir {
            get {
                return ResourceManager.GetString("Exception_SettingsPathEscapesAllowedDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setup file URL could not be found 的本地化字符串。
        /// </summary>
        public static string Exception_SetupFileUrlNotFound {
            get {
                return ResourceManager.GetString("Exception_SetupFileUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded resource failed SHA256 validation. Expected {0}, got {1}. 的本地化字符串。
        /// </summary>
        public static string Exception_SHA256ValidationFailed {
            get {
                return ResourceManager.GetString("Exception_SHA256ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table data cannot be empty 的本地化字符串。
        /// </summary>
        public static string Exception_TableDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_TableDataCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag name cannot be null or empty 的本地化字符串。
        /// </summary>
        public static string Exception_TagNameNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_TagNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature array must have exactly 10 elements 的本地化字符串。
        /// </summary>
        public static string Exception_TempArrayMustBe10 {
            get {
                return ResourceManager.GetString("Exception_TempArrayMustBe10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undefined value received: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_UndefinedValueReceived {
            get {
                return ResourceManager.GetString("Exception_UndefinedValueReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown battery state: {0} 的本地化字符串。
        /// </summary>
        public static string Exception_UnknownBatteryState {
            get {
                return ResourceManager.GetString("Exception_UnknownBatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown hive. 的本地化字符串。
        /// </summary>
        public static string Exception_UnknownHive {
            get {
                return ResourceManager.GetString("Exception_UnknownHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to parse version from tag name: &apos;{0}&apos;. Expected format: &apos;3.0.1&apos; 的本地化字符串。
        /// </summary>
        public static string Exception_UnparseableVersionFormat {
            get {
                return ResourceManager.GetString("Exception_UnparseableVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported power mode {0} 的本地化字符串。
        /// </summary>
        public static string Exception_UnsupportedPowerMode {
            get {
                return ResourceManager.GetString("Exception_UnsupportedPowerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update package integrity check failed: no SHA256 hash available for update {0}. Integrity check is required for security. 的本地化字符串。
        /// </summary>
        public static string Exception_UpdateNoSHA256Hash {
            get {
                return ResourceManager.GetString("Exception_UpdateNoSHA256Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update package integrity check failed. Expected SHA256: {0}, Computed: {1} 的本地化字符串。
        /// </summary>
        public static string Exception_UpdateSHA256Mismatch {
            get {
                return ResourceManager.GetString("Exception_UpdateSHA256Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wildcard deletion is restricted 的本地化字符串。
        /// </summary>
        public static string Exception_WildcardDeletionRestricted {
            get {
                return ResourceManager.GetString("Exception_WildcardDeletionRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call failed: {0} [scope={1}, query={2}, methodName={3}] 的本地化字符串。
        /// </summary>
        public static string Exception_WmiCallFailed {
            get {
                return ResourceManager.GetString("Exception_WmiCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call failed: {0}. [scope={1}, query={2}, methodName={3}] 的本地化字符串。
        /// </summary>
        public static string Exception_WmiCallFailedDot {
            get {
                return ResourceManager.GetString("Exception_WmiCallFailedDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WMI class or namespace not available [scope={0}, query={1}] 的本地化字符串。
        /// </summary>
        public static string Exception_WmiClassNotAvailable {
            get {
                return ResourceManager.GetString("Exception_WmiClassNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WMI feature value is unavailable for {0}. 的本地化字符串。
        /// </summary>
        public static string Exception_WmiFeatureUnavailable {
            get {
                return ResourceManager.GetString("Exception_WmiFeatureUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No results in query 的本地化字符串。
        /// </summary>
        public static string Exception_WmiNoResults {
            get {
                return ResourceManager.GetString("Exception_WmiNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read failed: {0} [scope={1}, query={2}] 的本地化字符串。
        /// </summary>
        public static string Exception_WmiReadFailed {
            get {
                return ResourceManager.GetString("Exception_WmiReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string FanMaxSpeedState_Off {
            get {
                return ResourceManager.GetString("FanMaxSpeedState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string FanMaxSpeedState_On {
            get {
                return ResourceManager.GetString("FanMaxSpeedState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle 的本地化字符串。
        /// </summary>
        public static string FanMaxSpeedState_Toggle {
            get {
                return ResourceManager.GetString("FanMaxSpeedState_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string FlipToStartState_Off {
            get {
                return ResourceManager.GetString("FlipToStartState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string FlipToStartState_On {
            get {
                return ResourceManager.GetString("FlipToStartState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string FnLockState_Off {
            get {
                return ResourceManager.GetString("FnLockState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string FnLockState_On {
            get {
                return ResourceManager.GetString("FnLockState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered Off 的本地化字符串。
        /// </summary>
        public static string GPUController_PoweredOff {
            get {
                return ResourceManager.GetString("GPUController_PoweredOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered On 的本地化字符串。
        /// </summary>
        public static string GPUController_PoweredOn {
            get {
                return ResourceManager.GetString("GPUController_PoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string HardwareSensorsState_Off {
            get {
                return ResourceManager.GetString("HardwareSensorsState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string HardwareSensorsState_On {
            get {
                return ResourceManager.GetString("HardwareSensorsState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string HDRState_Off {
            get {
                return ResourceManager.GetString("HDRState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string HDRState_On {
            get {
                return ResourceManager.GetString("HDRState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dGPU 的本地化字符串。
        /// </summary>
        public static string HybridModeState_Off {
            get {
                return ResourceManager.GetString("HybridModeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid 的本地化字符串。
        /// </summary>
        public static string HybridModeState_On {
            get {
                return ResourceManager.GetString("HybridModeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid-Auto 的本地化字符串。
        /// </summary>
        public static string HybridModeState_OnAuto {
            get {
                return ResourceManager.GetString("HybridModeState_OnAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid-iGPU 的本地化字符串。
        /// </summary>
        public static string HybridModeState_OnIGPUOnly {
            get {
                return ResourceManager.GetString("HybridModeState_OnIGPUOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AC Adapter 的本地化字符串。
        /// </summary>
        public static string InstantBootState_AcAdapter {
            get {
                return ResourceManager.GetString("InstantBootState_AcAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AC and USB PD 的本地化字符串。
        /// </summary>
        public static string InstantBootState_AcAdapterAndUsbPowerDelivery {
            get {
                return ResourceManager.GetString("InstantBootState_AcAdapterAndUsbPowerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string InstantBootState_Off {
            get {
                return ResourceManager.GetString("InstantBootState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USB Power Delivery 的本地化字符串。
        /// </summary>
        public static string InstantBootState_UsbPowerDelivery {
            get {
                return ResourceManager.GetString("InstantBootState_UsbPowerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery Saving 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Battery_Saving {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Battery_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intelligent Cooling 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Cooling {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extreme Performance 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Extreme_Performance {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Extreme_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geek 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Geek {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Geek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aurora Sync 的本地化字符串。
        /// </summary>
        public static string LampEffect_AuroraSync {
            get {
                return ResourceManager.GetString("LampEffect_AuroraSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breathe 的本地化字符串。
        /// </summary>
        public static string LampEffect_Breathe {
            get {
                return ResourceManager.GetString("LampEffect_Breathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Pattern 的本地化字符串。
        /// </summary>
        public static string LampEffect_CustomPattern {
            get {
                return ResourceManager.GetString("LampEffect_CustomPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gradient 的本地化字符串。
        /// </summary>
        public static string LampEffect_Gradient {
            get {
                return ResourceManager.GetString("LampEffect_Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meteor 的本地化字符串。
        /// </summary>
        public static string LampEffect_Meteor {
            get {
                return ResourceManager.GetString("LampEffect_Meteor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow 的本地化字符串。
        /// </summary>
        public static string LampEffect_Rainbow {
            get {
                return ResourceManager.GetString("LampEffect_Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow Wave 的本地化字符串。
        /// </summary>
        public static string LampEffect_RainbowWave {
            get {
                return ResourceManager.GetString("LampEffect_RainbowWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ripple 的本地化字符串。
        /// </summary>
        public static string LampEffect_Ripple {
            get {
                return ResourceManager.GetString("LampEffect_Ripple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sparkle 的本地化字符串。
        /// </summary>
        public static string LampEffect_Sparkle {
            get {
                return ResourceManager.GetString("LampEffect_Sparkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spiral Rainbow 的本地化字符串。
        /// </summary>
        public static string LampEffect_SpiralRainbow {
            get {
                return ResourceManager.GetString("LampEffect_SpiralRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        public static string LampEffect_Static {
            get {
                return ResourceManager.GetString("LampEffect_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wave 的本地化字符串。
        /// </summary>
        public static string LampEffect_Wave {
            get {
                return ResourceManager.GetString("LampEffect_Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string MicrophoneState_Off {
            get {
                return ResourceManager.GetString("MicrophoneState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string MicrophoneState_On {
            get {
                return ResourceManager.GetString("MicrophoneState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alt 的本地化字符串。
        /// </summary>
        public static string ModifierKey_Alt {
            get {
                return ResourceManager.GetString("ModifierKey_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl 的本地化字符串。
        /// </summary>
        public static string ModifierKey_Ctrl {
            get {
                return ResourceManager.GetString("ModifierKey_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift 的本地化字符串。
        /// </summary>
        public static string ModifierKey_Shift {
            get {
                return ResourceManager.GetString("ModifierKey_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnostics only (no system network changes) 的本地化字符串。
        /// </summary>
        public static string NetworkAcceleration_Status_DiagnosticsOnly {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_DiagnosticsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off (default) 的本地化字符串。
        /// </summary>
        public static string NetworkAcceleration_Status_Off {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running ({0}) loopback:{1} 的本地化字符串。
        /// </summary>
        public static string NetworkAcceleration_Status_Running {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped ({0}) 的本地化字符串。
        /// </summary>
        public static string NetworkAcceleration_Status_Stopped {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Worker binary not found — build/install UniversalDeviceToolkit.NetworkProxy.exe 的本地化字符串。
        /// </summary>
        public static string NetworkAcceleration_Status_WorkerMissing {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Status_WorkerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long 的本地化字符串。
        /// </summary>
        public static string NotificationDuration_Long {
            get {
                return ResourceManager.GetString("NotificationDuration_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string NotificationDuration_Normal {
            get {
                return ResourceManager.GetString("NotificationDuration_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Short 的本地化字符串。
        /// </summary>
        public static string NotificationDuration_Short {
            get {
                return ResourceManager.GetString("NotificationDuration_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomRight {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_Center {
            get {
                return ResourceManager.GetString("NotificationPosition_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_CenterLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_CenterRight {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopRight {
            get {
                return ResourceManager.GetString("NotificationPosition_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string OneLevelWhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("OneLevelWhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string OneLevelWhiteKeyboardBacklightState_On {
            get {
                return ResourceManager.GetString("OneLevelWhiteKeyboardBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk 1 Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_Disk1Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Disk1Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk 2 Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_Disk2Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Disk2Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-Core Clock 的本地化字符串。
        /// </summary>
        public static string OsdItem_E_Core_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_E_Core_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan 的本地化字符串。
        /// </summary>
        public static string OsdItem_Fan {
            get {
                return ResourceManager.GetString("OsdItem_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FPS 的本地化字符串。
        /// </summary>
        public static string OsdItem_Fps {
            get {
                return ResourceManager.GetString("OsdItem_Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Time 的本地化字符串。
        /// </summary>
        public static string OsdItem_FrameTime {
            get {
                return ResourceManager.GetString("OsdItem_FrameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequency 的本地化字符串。
        /// </summary>
        public static string OsdItem_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1% Low 的本地化字符串。
        /// </summary>
        public static string OsdItem_LowFps {
            get {
                return ResourceManager.GetString("OsdItem_LowFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_MemoryTemperature {
            get {
                return ResourceManager.GetString("OsdItem_MemoryTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Motherboard Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_MotherboardTemperature {
            get {
                return ResourceManager.GetString("OsdItem_MotherboardTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P-Core Clock 的本地化字符串。
        /// </summary>
        public static string OsdItem_P_Core_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_P_Core_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power 的本地化字符串。
        /// </summary>
        public static string OsdItem_Power {
            get {
                return ResourceManager.GetString("OsdItem_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Utilization 的本地化字符串。
        /// </summary>
        public static string OsdItem_Utilization {
            get {
                return ResourceManager.GetString("OsdItem_Utilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VRAM Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_VramTemperature {
            get {
                return ResourceManager.GetString("OsdItem_VramTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VRAM Utilization 的本地化字符串。
        /// </summary>
        public static string OsdItem_VramUtilization {
            get {
                return ResourceManager.GetString("OsdItem_VramUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string OsdState_Hidden {
            get {
                return ResourceManager.GetString("OsdState_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string OsdState_Show {
            get {
                return ResourceManager.GetString("OsdState_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle State 的本地化字符串。
        /// </summary>
        public static string OsdState_Toggle {
            get {
                return ResourceManager.GetString("OsdState_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string OverdriveState_Off {
            get {
                return ResourceManager.GetString("OverdriveState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string OverdriveState_On {
            get {
                return ResourceManager.GetString("OverdriveState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string PanelLogoBacklightState_Off {
            get {
                return ResourceManager.GetString("PanelLogoBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string PanelLogoBacklightState_On {
            get {
                return ResourceManager.GetString("PanelLogoBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string PortsBacklightState_Off {
            get {
                return ResourceManager.GetString("PortsBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string PortsBacklightState_On {
            get {
                return ResourceManager.GetString("PortsBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string PowerModeMappingMode_Disabled {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Power Mode 的本地化字符串。
        /// </summary>
        public static string PowerModeMappingMode_WindowsPowerMode {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_WindowsPowerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Power Plan 的本地化字符串。
        /// </summary>
        public static string PowerModeMappingMode_WindowsPowerPlan {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_WindowsPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Balance {
            get {
                return ResourceManager.GetString("PowerModeState_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extreme 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Extreme {
            get {
                return ResourceManager.GetString("PowerModeState_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string PowerModeState_GodMode {
            get {
                return ResourceManager.GetString("PowerModeState_GodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Performance {
            get {
                return ResourceManager.GetString("PowerModeState_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quiet 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Quiet {
            get {
                return ResourceManager.GetString("PowerModeState_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Hz 的本地化字符串。
        /// </summary>
        public static string RefreshRate_DisplayName_Format {
            get {
                return ResourceManager.GetString("RefreshRate_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} × {1} 的本地化字符串。
        /// </summary>
        public static string Resolution_DisplayName_Format {
            get {
                return ResourceManager.GetString("Resolution_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightBrightness_High {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightBrightness_Low {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breath 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Breath {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Smooth {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Static {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wave Left 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_WaveLTR {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_WaveLTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wave Right 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_WaveRTL {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_WaveRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset 4 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Four {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Off {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset 1 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_One {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset 3 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Three {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset 2 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Two {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Fast {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fastest 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Fastest {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Slow {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slowest 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Slowest {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Slowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute 的本地化字符串。
        /// </summary>
        public static string SpeakerState_Mute {
            get {
                return ResourceManager.GetString("SpeakerState_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmute 的本地化字符串。
        /// </summary>
        public static string SpeakerState_Unmute {
            get {
                return ResourceManager.GetString("SpeakerState_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_High {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Low {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Medium {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Off {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom to Top 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_BottomToTop {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_BottomToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clockwise 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_Clockwise {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Counter Clockwise 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_CounterClockwise {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left to Right 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_LeftToRight {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right to Left 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_RightToLeft {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top to Bottom 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_TopToBottom {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_TopToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Always {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Bounce 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AudioBounce {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AudioBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Ripple 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AudioRipple {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AudioRipple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aurora Sync 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AuroraSync {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AuroraSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Change 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorChange {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Pulse 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorPulse {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Wave 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorWave {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rain 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Rain {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow Screw 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_RainbowScrew {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_RainbowScrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow Wave 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_RainbowWave {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_RainbowWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ripple 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Ripple {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Ripple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Smooth {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Type {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed1 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed2 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed3 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Style 的本地化字符串。
        /// </summary>
        public static string ThemeStylePreset_Default {
            get {
                return ResourceManager.GetString("ThemeStylePreset_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forest Tech 的本地化字符串。
        /// </summary>
        public static string ThemeStylePreset_Forest {
            get {
                return ResourceManager.GetString("ThemeStylePreset_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Midnight Neon 的本地化字符串。
        /// </summary>
        public static string ThemeStylePreset_Midnight {
            get {
                return ResourceManager.GetString("ThemeStylePreset_Midnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Official Cool 的本地化字符串。
        /// </summary>
        public static string ThemeStylePreset_Official {
            get {
                return ResourceManager.GetString("ThemeStylePreset_Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string TouchpadLockState_Off {
            get {
                return ResourceManager.GetString("TouchpadLockState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string TouchpadLockState_On {
            get {
                return ResourceManager.GetString("TouchpadLockState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerDay {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every hour 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerHour {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerMonth {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 3 hours 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerThreeHours {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerThreeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 12 hours 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerTwelveHours {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerTwelveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerWeek {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_High {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_Low {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 macOS 的本地化字符串。
        /// </summary>
        public static string WindowBackdropStyle_macOS {
            get {
                return ResourceManager.GetString("WindowBackdropStyle_macOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 的本地化字符串。
        /// </summary>
        public static string WindowBackdropStyle_Windows {
            get {
                return ResourceManager.GetString("WindowBackdropStyle_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait for the current optimization to finish. 的本地化字符串。
        /// </summary>
        public static string WindowsOptimizationPage_Optimization_Busy_Wait {
            get {
                return ResourceManager.GetString("WindowsOptimizationPage_Optimization_Busy_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The change could not be verified. Administrator privileges may be required. 的本地化字符串。
        /// </summary>
        public static string WindowsOptimizationPage_Optimization_NotVerified {
            get {
                return ResourceManager.GetString("WindowsOptimizationPage_Optimization_NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string WinKeyState_Off {
            get {
                return ResourceManager.GetString("WinKeyState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string WinKeyState_On {
            get {
                return ResourceManager.GetString("WinKeyState_On", resourceCulture);
            }
        }
    }
}
