# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SSC-STUDIO.UniversalDeviceToolkit
PackageVersion: 3.6.15
InstallerType: inno
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-04-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SSC-STUDIO/UniversalDeviceToolkit/releases/download/v3.6.15/UniversalDeviceToolkit_v3.6.15_Setup.exe
  InstallerSha256: 0942197944ABC533AE317573BCBD3CC8FE303D494B5B21D20C9578B545AF9A7C
ManifestType: installer
ManifestVersion: 1.10.0
