# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SSC-STUDIO.UniversalDeviceToolkit
PackageVersion: 4.0.0
InstallerType: inno
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-05-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SSC-STUDIO/UniversalDeviceToolkit/releases/download/v4.0.0/UniversalDeviceToolkit_v4.0.0_Setup.exe
  InstallerSha256: A4B1B6CD6FABB3960C96F610F294DE9D5A9DEEFDD2EDE4F9F96634511C1F2CF2
ManifestType: installer
ManifestVersion: 1.10.0
