<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(UDTTargetFramework)</TargetFramework>
    <RootNamespace>LenovoLegionToolkit.Lib.Plugins</RootNamespace>
    <AssemblyName>LenovoLegionToolkit.Lib.Plugins</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="IAppStartupPlugin.cs" />
    <Compile Remove="IOptimizationCategoryProvider.cs" />
    <Compile Remove="IPlugin.cs" />
    <Compile Remove="IPluginConfiguration.cs" />
    <Compile Remove="IPluginHostContext.cs" />
    <Compile Remove="IPluginPage.cs" />
    <Compile Remove="PluginBase.cs" />
    <Compile Remove="PluginConfiguration.cs" />
    <Compile Remove="PluginHostContext.cs" />
    <Compile Remove="PluginHostMode.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UniversalDeviceToolkit.Lib\UniversalDeviceToolkit.Lib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Resource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
