<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(LLTTargetFramework)</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <Platforms>x64</Platforms>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
	    <Copyright>© 2026 Lenovo Legion Toolkit Contributors</Copyright>
        <NeutralLanguage>en</NeutralLanguage>
    </PropertyGroup>
</Project>
