<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPluginToolProject>true</IsPluginToolProject>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PluginTooling.Core\PluginTooling.Core.csproj" />
  </ItemGroup>

</Project>
