namespace UniversalDeviceToolkit.Installer;

/// <summary>
/// Snapshot of the app's built-in device support catalog
/// (UniversalDeviceToolkit.Lib/DeviceSupport/LenovoDeviceSupportProvider.cs),
/// trimmed to the fields the installer matcher needs.
/// DevicePackSnapshotGuardTests fails when the app catalog drifts —
/// regenerate this file then (see the test for the dump command).
/// </summary>
internal sealed record DevicePackInfo(
    string Id,
    string DisplayName,
    string Vendor,
    string[] VendorAliases,
    string[] ModelKeywords,
    string[] MachineTypes,
    bool IsHardware);

internal static class DevicePackSnapshot
{
    public const string GenericBasicPackId = "generic-pc-basic";

    public static readonly DevicePackInfo[] Packs =
    [
        new("lenovo-legion-pro-7", "Lenovo Legion Pro 7", "LENOVO", [], ["Legion Pro 7", "Legion Pro 7i", "Legion Pro 7 16", "Legion Pro 7 18", "Y9000K", "R9000K", "Y9000K 2024", "Y9000K 2025", "Y9000K 2026", "R9000K 2024", "R9000K 2025", "R9000K 2026", "拯救者 Y9000K", "拯救者 R9000K", "Y9000P Ultimate", "Pro 7i"], ["83RU", "83F5", "83DE", "82WR", "82WQ", "82WS", "82WT", "83RS", "83RT", "83RV", "83RW", "83RX", "83RY", "83F4", "83F6", "83F7", "83F8", "83F9", "83FA", "83FB", "83FC", "83FD", "83S0", "83S1", "83S2", "83S3", "83S4", "83S5", "83S6", "83S7", "83S8", "83S9", "83T0", "83T1", "83T2", "83T3", "83T4", "83T5"], true),
        new("lenovo-legion-pro-5", "Lenovo Legion Pro 5", "LENOVO", [], ["Legion Pro 5", "Legion Pro 5i", "Legion Pro 5 16", "Y9000P", "R9000P", "Y9000P IRX9", "Y9000P IAX9", "Y9000P IRX10", "Y9000P IAX10", "Y9000P IRX11", "Y9000P IAX11", "Y9000P 2023", "Y9000P 2024", "Y9000P 2025", "Y9000P 2026", "R9000P 2023", "R9000P 2024", "R9000P 2025", "R9000P 2026", "拯救者 Y9000P", "拯救者 R9000P", "Pro 5i"], ["83LT", "83F3", "83DF", "83F2", "83LU", "82WM", "83NN", "82WK", "82JQ", "82RF", "82RG", "83DG", "83LR", "83LS", "83LV", "83LW", "83LX", "82SN", "82SM", "83J0", "83J1", "83J2", "83J3", "83J4", "83J5", "83J6", "83J7", "83M1", "83M2", "83M3", "83M4", "83M5", "83N3", "83N4", "83N5", "83P4", "83P5", "83P6", "83P7", "83P8", "83P9", "83Q0", "83Q1", "83Q2", "83Q3", "83Q4", "83Q5"], true),
        new("lenovo-legion-9", "Lenovo Legion 9", "LENOVO", [], ["Legion 9", "Legion 9i", "Legion 9 16", "Legion 9 18", "拯救者 Legion 9"], ["83G0", "83EY", "83EZ", "83G9", "83GA", "83GB", "83GC", "83GD", "83GE", "83GF", "83R0", "83R1", "83R2", "83R3", "83R4", "83R5"], true),
        new("lenovo-legion-7", "Lenovo Legion 7", "LENOVO", [], ["Legion 7", "Legion 7i", "Legion 7 16", "Legion Slim 7", "拯救者 Legion 7"], ["83KY", "82UH", "82TD", "82N6", "82N7", "83FE", "83FF", "83K0", "83K1", "83AG", "83K2", "83K3", "83K4", "83K5", "83L0", "83L1", "83L2", "83L3", "83U0", "83U1", "83U2", "83U3", "83U4", "83U5"], true),
        new("lenovo-legion-slim-5", "Lenovo Legion Slim 5", "LENOVO", [], ["Legion Slim 5", "Legion Slim 5i", "Legion Slim 7", "Legion Slim 7i", "拯救者 Slim"], ["83DH", "83EX", "82Y5", "82Y9", "82YA", "83D6", "83D0", "83D1", "83G5", "83G6", "83G7", "83G8", "83H6", "83H7", "83H8", "83H9", "83HA", "83HB", "83HC", "83HD", "83J8", "83J9", "83JA", "83JB", "83V0", "83V1", "83V2", "83V3", "83V4", "83V5"], true),
        new("lenovo-legion-go", "Lenovo Legion Go", "LENOVO", [], ["Legion Go", "Legion Go S", "Legion Go 2", "Legion Go Gen 2", "拯救者 Go"], ["83E1", "83N0", "83N1", "83L4", "83L5", "83L6", "83L7", "83L8", "83L9", "83W0", "83W1", "83W2", "83W3"], true),
        new("lenovo-loq", "Lenovo LOQ", "LENOVO", [], ["LOQ", "LOQ 15", "LOQ 16", "LOQ 17", "LOQ 15IRX", "LOQ 15IAX", "LOQ 15APH", "G5000", "拯救者 LOQ", "拯救者G5000", "拯救者 G5000"], ["83GS", "83GT", "83GU", "83GV", "83GW", "83JC", "83JD", "83JE", "83JF", "82XV", "82XW", "83DV", "83DW", "83DX", "83DY", "83AQ", "83AR", "83AS", "83GX", "83GY", "83GZ", "83H0", "83H1", "83H2", "83H3", "83H4", "83H5", "83JI", "83JK", "83JL", "83JM", "83JN", "83JP", "83JQ", "83JR", "83K6", "83K7", "83K8", "83K9", "83KA", "83KB", "83KC", "83KD", "83X0", "83X1", "83X2", "83X3", "83X4", "83X5"], true),
        new("lenovo-legion-5", "Lenovo Legion 5", "LENOVO", [], ["Legion 5", "Legion 5i", "Legion 5 Pro", "Legion 5a", "Legion 5 15", "Legion 5 16", "Legion 5 17", "Y7000", "Y7000P", "Y7000P 2020H", "Y7000P2020H", "Y7000P IRX9", "Y7000P IRX10", "Y7000P IRX11", "Y7000 2023", "Y7000 2024", "Y7000 2025", "Y7000 2026", "Y7000P 2023", "Y7000P 2024", "Y7000P 2025", "Y7000P 2026", "R7000", "R7000P", "R7000P 2021", "R7000P 2023", "R7000P 2024", "R7000P 2025", "R7000P 2026", "拯救者 Y7000", "拯救者 Y7000P", "拯救者 R7000", "拯救者 R7000P"], ["83F0", "83F1", "83M0", "83NX", "83N2", "83LY", "83EW", "83EG", "83JJ", "83JG", "83JH", "82RC", "82RB", "82TB", "83EF", "82RE", "82RD", "82AX", "82B0", "82GR", "82JU", "82JV", "82JW", "82JY", "82K0", "82K1", "82K2", "82N4", "82N5", "82NW", "83FG", "83FH", "83G1", "83G2", "83LL", "83LM", "83LN", "83DT", "83DU", "83C6", "83C7", "83M6", "83M7", "83M8", "83M9", "83MA", "83MB", "83MC", "83MD", "83N6", "83N7", "83N8", "83N9", "83NA", "83NB", "83NC", "83ND", "83P0", "83P1", "83P2", "83P3", "83PA", "83PB", "83PC", "83PD", "83Q6", "83Q7", "83Q8", "83Q9", "83QA", "83QB", "83QC", "83QD", "82B1", "82B2", "82B3", "82B4", "82B5", "83Y0", "83Y1", "83Y2", "83Y3", "83Y4", "83Y5"], true),
        new("lenovo-chromebook-basic", "Lenovo Chromebook Basic", "LENOVO", [], ["Chromebook", "Chromebook Plus", "Flex Chromebook", "IdeaPad Chromebook"], [], false),
        new("lenovo-ideapad-gaming", "Lenovo IdeaPad Gaming", "LENOVO", [], ["IdeaPad Gaming", "IdeaPad Gaming 3", "IdeaPad Gaming 3i", "IdeaPad Gaming 3 15", "IdeaPad Gaming 3 16", "IdeaPad Gaming 3 15IAH7", "IdeaPad Gaming 3 16IAH7", "拯救者 IdeaPad Gaming", "小新 Gaming"], ["82EY", "82S9", "82SA", "82SB", "82SC", "82SD", "82SE", "82SF", "83C8", "83C9", "83CA", "83CB", "83CC", "83CD", "83Z0", "83Z1", "83Z2", "83Z3"], true),
        new("lenovo-ideapad", "Lenovo IdeaPad", "LENOVO", [], ["IdeaPad", "IdeaPad Slim", "IdeaPad Flex", "IdeaPad 1", "IdeaPad 3", "IdeaPad 5", "IdeaPad Pro"], [], false),
        new("lenovo-thinkbook", "Lenovo ThinkBook", "LENOVO", [], ["ThinkBook", "ThinkBook 14", "ThinkBook 16", "ThinkBook Plus"], [], false),
        new("lenovo-yoga", "Lenovo YOGA", "LENOVO", [], ["YOGA", "Yoga", "Yoga Pro", "Yoga Slim", "Yoga Book", "Yoga 7", "Yoga 9"], [], false),
        new("lenovo-legion-desktop-basic", "Lenovo Legion Desktop Basic", "LENOVO", [], ["Legion T", "Legion Tower", "Legion C", "Legion Desktop"], [], false),
        new("lenovo-legacy-limited", "Lenovo Legacy Limited", "LENOVO", [], ["Legion"], [], true),
        new("lenovo-thinkpad-basic", "Lenovo ThinkPad Basic", "LENOVO", [], ["ThinkPad", "ThinkPad P", "ThinkPad T", "ThinkPad X", "ThinkPad E", "ThinkPad L", "ThinkPad Z", "ThinkPad X1", "ThinkPad X1 Carbon", "ThinkPad X1 Yoga", "ThinkPad T14", "ThinkPad T16", "ThinkPad P14s", "ThinkPad P16", "ThinkPad E14", "ThinkPad E16", "ThinkPad L14", "ThinkPad L16"], [], false),
        new("lenovo-thinkcentre-basic", "Lenovo ThinkCentre Basic", "LENOVO", [], ["ThinkCentre", "ThinkCentre M", "ThinkCentre Neo"], [], false),
        new("lenovo-thinkstation-basic", "Lenovo ThinkStation Basic", "LENOVO", [], ["ThinkStation", "ThinkStation P"], [], false),
        new("lenovo-ideacentre-basic", "Lenovo IdeaCentre Basic", "LENOVO", [], ["IdeaCentre", "Yoga AIO"], [], false),
        new("lenovo-xiaoxin-basic", "Lenovo XiaoXin Basic", "LENOVO", [], ["XiaoXin", "Xiaoxin", "小新"], [], false),
        new("lenovo-y-series-legacy", "Lenovo Y Series Legacy", "LENOVO", [], ["Lenovo Y", "Y Series"], [], false),
        new("lenovo-v-series-basic", "Lenovo V Series Basic", "LENOVO", [], ["Lenovo V", "V14", "V15", "V17"], [], false),
        new("lenovo-slim-basic", "Lenovo Slim Basic", "LENOVO", [], ["Lenovo Slim", "IdeaPad Slim", "Slim 7", "Slim 5"], [], false),
        new("motorola-lenovo-basic", "Motorola Lenovo Basic", "MOTOROLA", [], ["Legion", "ThinkPhone", "Moto"], [], false),
        new("asus-basic", "ASUS Basic", "ASUSTeK COMPUTER INC.", ["ASUS", "ASUSTeK COMPUTER INC", "ASUSTeK COMPUTER INCORPORATED", "ROG", "Republic of Gamers", "TUF Gaming"], ["ROG", "ROG Strix", "ROG Flow", "ROG Zephyrus", "ROG Ally", "ROG Ally X", "TUF", "TUF Gaming", "Zephyrus", "Strix", "VivoBook", "Vivobook", "Zenbook", "ProArt", "ExpertBook", "Chromebook", "Chromebook Plus"], [], false),
        new("dell-basic", "Dell Basic", "Dell Inc.", ["Dell", "Dell Computer Corporation", "Alienware"], ["Alienware", "Alienware m", "Alienware x", "XPS", "Inspiron", "Precision", "Latitude", "Dell G", "G15", "G16", "OptiPlex", "Vostro", "Chromebook", "Chromebook Plus"], [], false),
        new("hp-basic", "HP Basic", "HP", ["HP Inc.", "Hewlett-Packard", "Hewlett-Packard Company", "OMEN", "Victus"], ["OMEN", "Omen Max", "OMEN Transcend", "Victus", "Pavilion", "Envy", "EliteBook", "ProBook", "ZBook", "Spectre", "Dragonfly", "Chromebook", "Chromebook Plus"], [], false),
        new("acer-basic", "Acer Basic", "Acer", ["Acer Incorporated", "Acer Inc.", "Predator", "Nitro"], ["Predator", "Predator Helios", "Predator Triton", "Nitro", "Swift", "Aspire", "TravelMate", "ConceptD", "Extensa", "Spin", "Chromebook", "Chromebook Plus"], [], false),
        new("msi-basic", "MSI Basic", "Micro-Star International Co., Ltd.", ["MSI", "Micro-Star International", "MICRO-STAR INTERNATIONAL CO., LTD"], ["MSI", "Raider", "Stealth", "Vector", "Katana", "Cyborg", "Creator", "Prestige", "Modern", "Summit", "Crosshair", "Pulse", "Sword", "Thin"], [], false),
        new("microsoft-surface-basic", "Microsoft Surface Basic", "Microsoft Corporation", ["Microsoft"], ["Surface Laptop", "Surface Pro", "Surface Book", "Surface Studio", "Surface Go"], [], false),
        new("gigabyte-basic", "GIGABYTE Basic", "GIGABYTE", ["Gigabyte Technology Co., Ltd.", "Gigabyte Technology Co., Ltd", "AORUS"], ["AORUS", "AERO", "GIGABYTE G"], [], false),
        new("razer-basic", "Razer Basic", "Razer", ["Razer Inc.", "Razer Inc"], ["Blade", "Razer Book"], [], false),
        new("samsung-basic", "Samsung Basic", "SAMSUNG ELECTRONICS CO., LTD.", ["Samsung", "Samsung Electronics", "SAMSUNG ELECTRONICS CO., LTD"], ["Galaxy Book", "Notebook 9", "Galaxy Chromebook", "Chromebook", "Chromebook Plus"], [], false),
        new("google-chromebook-basic", "Google Chromebook Basic", "Google", ["Google LLC", "Google Inc.", "Google Inc"], ["Pixelbook", "Pixel Slate", "Chromebook", "Chromebook Plus"], [], false),
        new("apple-basic", "Apple Basic", "Apple Inc.", ["Apple", "Apple Computer, Inc."], ["MacBook", "MacBook Pro", "MacBook Air", "iMac", "Mac mini", "Mac Studio", "Mac Pro"], [], false),
        new("huawei-basic", "HUAWEI Basic", "HUAWEI", ["Huawei", "Huawei Technologies", "Huawei Technologies Co., Ltd.", "Huawei Technologies Co., Ltd"], ["MateBook", "MateBook X", "MateBook D", "MateBook E", "MateBook GT", "Qingyun"], [], false),
        new("xiaomi-basic", "Xiaomi Basic", "Xiaomi", ["Xiaomi Inc.", "Xiaomi Corporation", "Redmi", "TIMI"], ["Mi Notebook", "RedmiBook", "Redmi G", "Xiaomi Book", "Xiaomi Book Pro", "Book Pro"], [], false),
        new("realme-basic", "realme Basic", "realme", ["realme Chongqing MobileTelecommunications Corp., Ltd.", "realme"], ["realme Book"], [], false),
        new("infinix-basic", "Infinix Basic", "INFINIX", ["Infinix Mobility Limited", "Infinix"], ["INBook", "Inbook"], [], false),
        new("honor-basic", "HONOR Basic", "HONOR", ["Honor Device Co., Ltd.", "Honor Device Co., Ltd"], ["MagicBook"], [], false),
        new("lg-basic", "LG Basic", "LG Electronics", ["LG Electronics Inc.", "LG Electronics Inc", "LG"], ["gram", "UltraPC"], [], false),
        new("framework-basic", "Framework Basic", "Framework", ["Framework Computer Inc.", "Framework Computer"], ["Framework Laptop"], [], false),
        new("panasonic-basic", "Panasonic Basic", "Panasonic", ["Panasonic Corporation"], ["TOUGHBOOK", "Let's note", "Lets note"], [], false),
        new("dynabook-basic", "Dynabook Basic", "Dynabook Inc.", ["Dynabook", "TOSHIBA", "TOSHIBA CORPORATION"], ["Portégé", "Portege", "Tecra", "Satellite"], [], false),
        new("nec-lavie-basic", "NEC LAVIE Basic", "NEC", ["NEC Personal Computers, Ltd.", "NEC Personal Computers", "NEC Corporation", "LAVIE"], ["LAVIE", "LaVie", "VersaPro"], [], false),
        new("sharp-basic", "Sharp Basic", "SHARP", ["Sharp Corporation", "Sharp"], ["Mebius", "Dynabook", "Chromebook"], [], false),
        new("fujitsu-basic", "Fujitsu Basic", "FUJITSU", ["FUJITSU CLIENT COMPUTING LIMITED", "Fujitsu Client Computing Limited"], ["LIFEBOOK", "CELSIUS"], [], false),
        new("vaio-basic", "VAIO Basic", "VAIO Corporation", ["VAIO"], ["VAIO"], [], false),
        new("gateway-basic", "Gateway Basic", "Gateway", ["Gateway Inc.", "Acer Gateway"], ["Gateway"], [], false),
        new("chuwi-basic", "CHUWI Basic", "CHUWI", ["Chuwi Innovation And Technology", "CHUWI Innovation Limited"], ["HeroBook", "CoreBook", "MiniBook", "GemiBook", "FreeBook"], [], false),
        new("teclast-basic", "TECLAST Basic", "TECLAST", ["Teclast", "Guangzhou Shangke Information Technology"], ["F15", "F16", "F7", "X6"], [], false),
        new("jumper-basic", "Jumper Basic", "Jumper", ["Jumper Computer", "Jumper Tech"], ["EZbook", "EZpad"], [], false),
        new("medion-basic", "MEDION Basic", "MEDION", ["MEDION AG", "ERAZER"], ["ERAZER", "AKOYA"], [], false),
        new("xmg-schenker-basic", "XMG/SCHENKER Basic", "SCHENKER", ["Schenker Technologies GmbH", "XMG", "TUXEDO"], ["XMG", "SCHENKER", "TUXEDO", "InfinityBook", "Stellaris", "Pulse", "Polaris", "Aura"], [], false),
        new("hasee-basic", "Hasee Basic", "HASEE", ["Hasee", "Hasee Computer"], ["Hasee", "ZhanShen", "Zhan Shen"], [], false),
        new("thunderobot-basic", "THUNDEROBOT Basic", "THUNDEROBOT", ["Thunderobot", "Raytheon"], ["Thunderobot", "911", "Zero", "Black Warrior"], [], false),
        new("machenike-basic", "MACHENIKE Basic", "MACHENIKE", ["Machenike"], ["MACHENIKE", "Machenike", "T58", "F117", "L16"], [], false),
        new("colorful-basic", "COLORFUL Basic", "COLORFUL", ["Colorful Technology And Development Co., Ltd.", "Colorful"], ["COLORFUL", "Evol", "X15", "MEOW"], [], false),
        new("maibenben-basic", "MAIBENBEN Basic", "MAIBENBEN", ["Maibenben", "MaiBenBen"], ["Maibenben", "MaiBook", "Xiaomai"], [], false),
        new("mechrevo-basic", "MECHREVO Basic", "MECHREVO", ["Mechanical Revolution", "MECHREVO INC.", "Tongfang", "THTF", "Tsinghua Tongfang"], ["MECHREVO", "Mechanical Revolution", "Jiaolong", "Kuangshi", "Code", "Unbounded", "F1"], [], false),
        new("valve-handheld-basic", "Valve Handheld Basic", "Valve", ["Valve Corporation"], ["Steam Deck"], [], false),
        new("gpd-handheld-basic", "GPD Handheld Basic", "GPD", ["GamePad Digital", "Shenzhen GPD Technology Co., Ltd."], ["GPD WIN", "GPD Win", "Win Max", "Win Mini", "Pocket", "Duo"], [], false),
        new("ayaneo-handheld-basic", "AYANEO Handheld Basic", "AYANEO", ["AYANEO", "AOKZOE", "Ayn Technologies", "AYN"], ["AYANEO", "AOKZOE", "Loki", "NEXT", "Air Plus", "Odin", "Odin2"], [], false),
        new("anbernic-handheld-basic", "Anbernic Handheld Basic", "Anbernic", ["ANBERNIC", "Shenzhen Yangliming Electronic Technology"], ["Anbernic", "RG35", "RG40", "RG505", "RG552", "RG556", "RG Arc", "Win600"], [], false),
        new("retroid-handheld-basic", "Retroid Handheld Basic", "Retroid", ["RETROID", "Moorechip Technologies", "GoRetroid"], ["Retroid", "Retroid Pocket", "Pocket 4", "Pocket 5"], [], false),
        new("orange-pi-handheld-basic", "Orange Pi Handheld Basic", "Orange Pi", ["Shenzhen Xunlong Software", "Xunlong", "OrangePi", "Orange Pi"], ["Orange Pi", "OrangePi", "Orange Pi Neo"], [], false),
        new("one-netbook-handheld-basic", "ONE-NETBOOK Handheld Basic", "ONE-NETBOOK", ["One-Netbook", "ONE-NETBOOK Technology", "ONEXPLAYER", "OneXPlayer"], ["OneXPlayer", "ONEXPLAYER", "One-Netbook", "OneMix", "OneGx"], [], false),
        new("minisforum-basic", "MINISFORUM Basic", "MINISFORUM", ["Micro Computer (HK) Tech Limited", "Minisforum"], ["MINISFORUM", "UM", "HX", "Venus Series"], [], false),
        new("beelink-basic", "Beelink Basic", "Beelink", ["AZW", "Shenzhen AZW Technology Co., Ltd.", "Beelink"], ["SER", "GTR", "EQ", "Beelink"], [], false),
        new("geekom-basic", "GEEKOM Basic", "GEEKOM", ["Geekom", "GEEKOM"], ["Mini IT", "MiniAir", "A7", "GT"], [], false),
        new("gmktec-basic", "GMKtec Basic", "GMKtec", ["GMK", "GMKtec", "Shenzhen GMKtec"], ["NucBox", "EVO-X", "K8", "K6", "M7", "M5"], [], false),
        new("morefine-basic", "Morefine Basic", "Morefine", ["MORE FINE", "Shenzhen Morefine"], ["Morefine", "S500", "S600", "M600", "M9"], [], false),
        new("acemagic-basic", "ACEMAGIC Basic", "ACEMAGIC", ["Ace Magician", "ACEMAGICIAN", "ACEMAGIC", "KAMRUI"], ["ACEMAGIC", "Kron", "F5A", "Tank", "AM", "AD", "S1"], [], false),
        new("aoostar-basic", "AOOSTAR Basic", "AOOSTAR", ["AOOSTAR", "Aoostar"], ["GEM", "GOD", "WTR", "MN", "N1", "R7 NAS"], [], false),
        new("regional-mini-pc-basic", "Regional Mini PC Basic", "TRIGKEY", ["TRIGKEY", "Trigkey", "BOSGAME", "Bosgame", "FIREBAT", "Firebat", "CHATREEY", "Chatreey", "SZBOX", "FEVM", "NiPoGi", "Nipogi", "PELADN", "KODLIX", "Topdon", "KTC"], [], [], false),
        new("mele-basic", "MeLE Basic", "MeLE", ["Mele", "MeLE Technologies", "Shenzhen MeLE Digital Technology"], ["Quieter", "Overclock", "PCG", "Mini PC"], [], false),
        new("bmax-ninkear-basic", "BMAX/Ninkear Basic", "BMAX", ["BMAX", "Ninkear", "KUU", "N-one", "N-ONE", "MALLRACE"], ["BMAX", "Ninkear", "KUU", "N-one", "N-one Nbook", "Mini PC", "Y13", "Y14", "X14", "X15"], [], false),
        new("zotac-basic", "ZOTAC Basic", "ZOTAC", ["ZOTAC International"], ["ZBOX", "MAGNUS", "ZOTAC"], [], false),
        new("system76-basic", "System76 Basic", "System76", ["System76, Inc.", "System 76", "Notebook"], ["Adder WS", "addw", "Bonobo WS", "bonw", "Darter Pro", "darp", "Galago Pro", "galp", "Gazelle", "gaze", "Kudu", "Lemur Pro", "lemp", "Meerkat", "meer", "Oryx Pro", "oryp", "Pangolin Pro", "panp", "Serval WS", "serw", "Thelio"], [], false),
        new("star-labs-basic", "Star Labs Basic", "Star Labs", ["Star Labs Systems", "StarLabs", "Star Labs Systems Ltd"], ["StarFighter", "StarBook", "StarLite", "StarLite Mk", "Byte"], [], false),
        new("slimbook-basic", "Slimbook Basic", "SLIMBOOK", ["Slimbook", "Slimbook S.L.", "Slimbook SL"], ["Elemental", "Excalibur", "EVO", "Executive", "Creative", "KDE Slimbook", "Fedora Slimbook", "Manjaro Slimbook", "Slimbook One", "Slimbook Zero"], [], false),
        new("clevo-tongfang-basic", "Clevo/Tongfang Basic", "CLEVO", ["Notebook", "Tongfang", "Eluktronics", "MECHREVO", "THUNDEROBOT", "Hasee", "SAGER"], ["MECHREVO", "THUNDEROBOT", "Hasee", "SAGER", "Eluktronics", "Maingear"], [], false),
        new("eluktronics-basic", "Eluktronics Basic", "Eluktronics", ["Eluktronics", "Eluktronics Inc."], ["Eluktronics", "RP", "MAX", "MECH", "Prometheus", "Hydroc"], [], false),
        new("maingear-basic", "MAINGEAR Basic", "MAINGEAR", ["Maingear", "MAINGEAR"], ["MAINGEAR", "Vector", "ML", "MG"], [], false),
        new("monster-tulpar-basic", "Monster/Tulpar Basic", "Monster", ["Monster Notebook", "Monster Computer", "Tulpar"], ["Tulpar", "Abra", "Semruk", "Huma"], [], false),
        new("dream-machines-basic", "Dream Machines Basic", "Dream Machines", ["Dream Machines", "Dream Machines Sp. z o.o."], ["Dream Machines", "RG", "RT", "RX", "RS"], [], false),
        new("pcspecialist-basic", "PCSpecialist Basic", "PCSpecialist", ["PC Specialist", "PC Specialist Ltd", "PCSpecialist"], ["Recoil", "Defiance", "Ionico", "Elimina", "Lafite"], [], false),
        new("eurocom-basic", "Eurocom Basic", "EUROCOM", ["Eurocom", "Eurocom Corporation"], ["Sky", "Nightsky", "Raptor", "Commander", "Panther"], [], false),
        new("origin-pc-basic", "Origin PC Basic", "Origin PC", ["ORIGIN PC", "OriginPC", "Corsair"], ["EON", "EON16", "EON17", "NS", "NT"], [], false),
        new("corsair-basic", "Corsair Basic", "Corsair", ["CORSAIR", "Corsair Memory, Inc.", "Corsair Components, Inc."], ["Voyager", "Corsair One", "Vengeance"], [], false),
        new("cyberpower-ibuypower-basic", "CyberPower/iBUYPOWER Basic", "CyberPowerPC", ["CyberPowerPC", "CyberPower Inc.", "iBUYPOWER", "iBUYPOWER Computer"], ["Tracer", "Gamer", "Slate", "Y60", "RDY"], [], false),
        new("casper-excalibur-basic", "Casper/Excalibur Basic", "Casper", ["Casper Bilgisayar", "Casper", "Excalibur"], ["Excalibur", "Nirvana"], [], false),
        new("nexstgo-avita-basic", "Nexstgo/Avita Basic", "Nexstgo", ["Nexstgo", "Nexstgo Company Limited", "Avita", "AVITA"], ["AVITA", "Avita", "LIBER", "ADMIROR", "PURA"], [], false),
        new("positivo-basic", "Positivo Basic", "Positivo", ["Positivo Tecnologia", "Positivo Informatica", "Positivo"], ["Motion", "Vision", "Master", "Duo"], [], false),
        new("wortmann-terra-basic", "Wortmann/TERRA Basic", "Wortmann", ["Wortmann AG", "WORTMANN", "TERRA"], ["TERRA", "Mobile", "Pad", "PC"], [], false),
        new("universal-workstation-basic", "Universal Workstation Basic", "*", [], ["Workstation", "Precision", "ZBook", "ThinkStation", "ProArt Station", "Creator Workstation"], [], false),
        new("universal-motherboard-basic", "Universal Motherboard Basic", "*", ["ASUSTeK COMPUTER INC.", "ASUS", "Gigabyte Technology Co., Ltd.", "GIGABYTE", "Micro-Star International Co., Ltd.", "MSI", "ASRock", "ASRock Inc.", "BIOSTAR", "EVGA", "NZXT", "Supermicro", "Super Micro Computer, Inc.", "Intel Corporation"], ["To Be Filled By O.E.M.", "SYS-", "MS-7", "B650", "X670", "Z690", "Z790", "B760", "X570", "B550", "TRX40", "WRX80"], [], false),
        new("universal-desktop-basic", "Universal Desktop Basic", "*", [], ["Desktop", "Tower", "Mini PC", "MiniPC", "AIO", "All-in-One", "All in One", "System Product Name"], [], false),
        new("universal-barebone-basic", "Universal Barebone Basic", "*", ["CLEVO", "Tongfang", "Notebook", "Hasee", "SAGER", "Eluktronics", "MECHREVO", "THUNDEROBOT"], ["Barebone", "Notebook", "To Be Filled By O.E.M.", "Default string"], [], false),
        new("generic-pc-basic", "Universal PC Basic", "*", [], [], [], false),
    ];
}
