# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SSC-STUDIO.LenovoLegionToolkit
PackageVersion: 4.2.1
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-06-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SSC-STUDIO/UniversalDeviceToolkit/releases/download/v4.2.1/LenovoLegionToolkit_v4.2.1_Setup.exe
  InstallerSha256: F477C775544B00A629B6459F2A882A35500329738A4E08D97A20CE2FA15577B2
ManifestType: installer
ManifestVersion: 1.10.0