<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(LLTTargetFramework)</TargetFramework>
    <RootNamespace>LenovoLegionToolkit.Lib.Plugins</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="IAppStartupPlugin.cs" />
    <Compile Remove="IOptimizationCategoryProvider.cs" />
    <Compile Remove="IPlugin.cs" />
    <Compile Remove="IPluginConfiguration.cs" />
    <Compile Remove="IPluginHostContext.cs" />
    <Compile Remove="IPluginPage.cs" />
    <Compile Remove="PluginBase.cs" />
    <Compile Remove="PluginConfiguration.cs" />
    <Compile Remove="PluginHostContext.cs" />
    <Compile Remove="PluginHostMode.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LenovoLegionToolkit.Lib\LenovoLegionToolkit.Lib.csproj" />
  </ItemGroup>
</Project>
