//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugins.BatteryHealth.Resources
{
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("Codex.ResourceGenerator", "1.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class Resource
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resource()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("LenovoLegionToolkit.Plugins.BatteryHealth.Resources.Resource", typeof(Resource).Assembly);
                }

                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string PluginName { get { return ResourceManager.GetString("PluginName", resourceCulture); } }
        public static string PluginDescription { get { return ResourceManager.GetString("PluginDescription", resourceCulture); } }
        public static string FeaturePageTitle { get { return ResourceManager.GetString("FeaturePageTitle", resourceCulture); } }
        public static string FeaturePageDescription { get { return ResourceManager.GetString("FeaturePageDescription", resourceCulture); } }
        public static string SettingsPageTitle { get { return ResourceManager.GetString("SettingsPageTitle", resourceCulture); } }
        public static string SettingsPageSubtitle { get { return ResourceManager.GetString("SettingsPageSubtitle", resourceCulture); } }
        public static string OverviewTitle { get { return ResourceManager.GetString("OverviewTitle", resourceCulture); } }
        public static string OverviewDescription { get { return ResourceManager.GetString("OverviewDescription", resourceCulture); } }
        public static string HealthPercentLabel { get { return ResourceManager.GetString("HealthPercentLabel", resourceCulture); } }
        public static string CycleCountLabel { get { return ResourceManager.GetString("CycleCountLabel", resourceCulture); } }
        public static string ChargeRemainingLabel { get { return ResourceManager.GetString("ChargeRemainingLabel", resourceCulture); } }
        public static string WearPercentLabel { get { return ResourceManager.GetString("WearPercentLabel", resourceCulture); } }
        public static string DesignedCapacityLabel { get { return ResourceManager.GetString("DesignedCapacityLabel", resourceCulture); } }
        public static string FullChargeCapacityLabel { get { return ResourceManager.GetString("FullChargeCapacityLabel", resourceCulture); } }
        public static string CapacityUnitMwh { get { return ResourceManager.GetString("CapacityUnitMwh", resourceCulture); } }
        public static string HealthStateLabel { get { return ResourceManager.GetString("HealthStateLabel", resourceCulture); } }
        public static string StatusHealthy { get { return ResourceManager.GetString("StatusHealthy", resourceCulture); } }
        public static string StatusWarning { get { return ResourceManager.GetString("StatusWarning", resourceCulture); } }
        public static string StatusCritical { get { return ResourceManager.GetString("StatusCritical", resourceCulture); } }
        public static string StatusNoBattery { get { return ResourceManager.GetString("StatusNoBattery", resourceCulture); } }
        public static string StatusUnknown { get { return ResourceManager.GetString("StatusUnknown", resourceCulture); } }
        public static string NoBatteryMessage { get { return ResourceManager.GetString("NoBatteryMessage", resourceCulture); } }
        public static string LoadingMessage { get { return ResourceManager.GetString("LoadingMessage", resourceCulture); } }
        public static string RefreshFailedMessage { get { return ResourceManager.GetString("RefreshFailedMessage", resourceCulture); } }
        public static string RefreshButton { get { return ResourceManager.GetString("RefreshButton", resourceCulture); } }
        public static string MonitoringCardTitle { get { return ResourceManager.GetString("MonitoringCardTitle", resourceCulture); } }
        public static string MonitoringCardDescription { get { return ResourceManager.GetString("MonitoringCardDescription", resourceCulture); } }
        public static string EnableMonitoringLabel { get { return ResourceManager.GetString("EnableMonitoringLabel", resourceCulture); } }
        public static string ThresholdsCardTitle { get { return ResourceManager.GetString("ThresholdsCardTitle", resourceCulture); } }
        public static string LowHealthThresholdLabel { get { return ResourceManager.GetString("LowHealthThresholdLabel", resourceCulture); } }
        public static string CriticalHealthThresholdLabel { get { return ResourceManager.GetString("CriticalHealthThresholdLabel", resourceCulture); } }
        public static string NotificationsCardTitle { get { return ResourceManager.GetString("NotificationsCardTitle", resourceCulture); } }
        public static string NotificationsCardDescription { get { return ResourceManager.GetString("NotificationsCardDescription", resourceCulture); } }
        public static string EnableNotificationLabel { get { return ResourceManager.GetString("EnableNotificationLabel", resourceCulture); } }
        public static string SaveButton { get { return ResourceManager.GetString("SaveButton", resourceCulture); } }
        public static string ReloadButton { get { return ResourceManager.GetString("ReloadButton", resourceCulture); } }
        public static string SettingsSaved { get { return ResourceManager.GetString("SettingsSaved", resourceCulture); } }
        public static string SettingsReloaded { get { return ResourceManager.GetString("SettingsReloaded", resourceCulture); } }
        public static string SettingsInvalidThresholds { get { return ResourceManager.GetString("SettingsInvalidThresholds", resourceCulture); } }
        public static string FormatHealthPercent { get { return ResourceManager.GetString("FormatHealthPercent", resourceCulture); } }
        public static string FormatWearPercent { get { return ResourceManager.GetString("FormatWearPercent", resourceCulture); } }
        public static string FormatChargeRemaining { get { return ResourceManager.GetString("FormatChargeRemaining", resourceCulture); } }
        public static string FormatCapacityMWh { get { return ResourceManager.GetString("FormatCapacityMWh", resourceCulture); } }
        public static string FormatCycleCount { get { return ResourceManager.GetString("FormatCycleCount", resourceCulture); } }
        public static string FormatThresholdValue { get { return ResourceManager.GetString("FormatThresholdValue", resourceCulture); } }
    }
}
