//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugins.AiAssistant
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Plugins.AiAssistant.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Assistant.
        /// </summary>
        public static string AiAssistant_PageTitle {
            get {
                return ResourceManager.GetString("AiAssistant_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-powered assistant with support for OpenAI and Ollama, providing chat, search, document generation, code assistance, translation, and summarization features..
        /// </summary>
        public static string AiAssistant_PageDescription {
            get {
                return ResourceManager.GetString("AiAssistant_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AiAssistant_Settings {
            get {
                return ResourceManager.GetString("AiAssistant_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure AI provider settings, API keys, and connection options..
        /// </summary>
        public static string AiAssistant_SettingsDescription {
            get {
                return ResourceManager.GetString("AiAssistant_SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Provider:.
        /// </summary>
        public static string AiAssistant_Provider {
            get {
                return ResourceManager.GetString("AiAssistant_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI.
        /// </summary>
        public static string AiAssistant_ProviderOpenAI {
            get {
                return ResourceManager.GetString("AiAssistant_ProviderOpenAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama (Local).
        /// </summary>
        public static string AiAssistant_ProviderOllama {
            get {
                return ResourceManager.GetString("AiAssistant_ProviderOllama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepSeek.
        /// </summary>
        public static string AiAssistant_ProviderDeepSeek {
            get {
                return ResourceManager.GetString("AiAssistant_ProviderDeepSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI API Key:.
        /// </summary>
        public static string AiAssistant_OpenAiApiKey {
            get {
                return ResourceManager.GetString("AiAssistant_OpenAiApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your OpenAI API key.
        /// </summary>
        public static string AiAssistant_OpenAiApiKeyPlaceholder {
            get {
                return ResourceManager.GetString("AiAssistant_OpenAiApiKeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI Model:.
        /// </summary>
        public static string AiAssistant_OpenAiModel {
            get {
                return ResourceManager.GetString("AiAssistant_OpenAiModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepSeek API Key:.
        /// </summary>
        public static string AiAssistant_DeepSeekApiKey {
            get {
                return ResourceManager.GetString("AiAssistant_DeepSeekApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepSeek Model:.
        /// </summary>
        public static string AiAssistant_DeepSeekModel {
            get {
                return ResourceManager.GetString("AiAssistant_DeepSeekModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama Base URL:.
        /// </summary>
        public static string AiAssistant_OllamaBaseUrl {
            get {
                return ResourceManager.GetString("AiAssistant_OllamaBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama Model:.
        /// </summary>
        public static string AiAssistant_OllamaModel {
            get {
                return ResourceManager.GetString("AiAssistant_OllamaModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string AiAssistant_TestConnection {
            get {
                return ResourceManager.GetString("AiAssistant_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status:.
        /// </summary>
        public static string AiAssistant_ConnectionStatus {
            get {
                return ResourceManager.GetString("AiAssistant_ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string AiAssistant_ConnectionStatusConnected {
            get {
                return ResourceManager.GetString("AiAssistant_ConnectionStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string AiAssistant_ConnectionStatusDisconnected {
            get {
                return ResourceManager.GetString("AiAssistant_ConnectionStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string AiAssistant_TabChat {
            get {
                return ResourceManager.GetString("AiAssistant_TabChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string AiAssistant_TabSearch {
            get {
                return ResourceManager.GetString("AiAssistant_TabSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string AiAssistant_TabDocument {
            get {
                return ResourceManager.GetString("AiAssistant_TabDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string AiAssistant_TabCode {
            get {
                return ResourceManager.GetString("AiAssistant_TabCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string AiAssistant_TabTranslate {
            get {
                return ResourceManager.GetString("AiAssistant_TabTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize.
        /// </summary>
        public static string AiAssistant_TabSummarize {
            get {
                return ResourceManager.GetString("AiAssistant_TabSummarize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message:.
        /// </summary>
        public static string AiAssistant_ChatPrompt {
            get {
                return ResourceManager.GetString("AiAssistant_ChatPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your search query:.
        /// </summary>
        public static string AiAssistant_SearchQuery {
            get {
                return ResourceManager.GetString("AiAssistant_SearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Topic:.
        /// </summary>
        public static string AiAssistant_DocumentTopic {
            get {
                return ResourceManager.GetString("AiAssistant_DocumentTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context (optional):.
        /// </summary>
        public static string AiAssistant_DocumentContext {
            get {
                return ResourceManager.GetString("AiAssistant_DocumentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Description:.
        /// </summary>
        public static string AiAssistant_CodeDescription {
            get {
                return ResourceManager.GetString("AiAssistant_CodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Language:.
        /// </summary>
        public static string AiAssistant_CodeLanguage {
            get {
                return ResourceManager.GetString("AiAssistant_CodeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code to Explain:.
        /// </summary>
        public static string AiAssistant_CodeToExplain {
            get {
                return ResourceManager.GetString("AiAssistant_CodeToExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Translate:.
        /// </summary>
        public static string AiAssistant_TranslateText {
            get {
                return ResourceManager.GetString("AiAssistant_TranslateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language:.
        /// </summary>
        public static string AiAssistant_TranslateTargetLanguage {
            get {
                return ResourceManager.GetString("AiAssistant_TranslateTargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Summarize:.
        /// </summary>
        public static string AiAssistant_SummarizeText {
            get {
                return ResourceManager.GetString("AiAssistant_SummarizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string AiAssistant_Send {
            get {
                return ResourceManager.GetString("AiAssistant_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string AiAssistant_Generate {
            get {
                return ResourceManager.GetString("AiAssistant_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain.
        /// </summary>
        public static string AiAssistant_Explain {
            get {
                return ResourceManager.GetString("AiAssistant_Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string AiAssistant_Translate {
            get {
                return ResourceManager.GetString("AiAssistant_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize.
        /// </summary>
        public static string AiAssistant_Summarize {
            get {
                return ResourceManager.GetString("AiAssistant_Summarize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AiAssistant_Cancel {
            get {
                return ResourceManager.GetString("AiAssistant_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response:.
        /// </summary>
        public static string AiAssistant_Response {
            get {
                return ResourceManager.GetString("AiAssistant_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key Required.
        /// </summary>
        public static string AiAssistant_Error_ApiKeyRequired {
            get {
                return ResourceManager.GetString("AiAssistant_Error_ApiKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your OpenAI API key in the settings..
        /// </summary>
        public static string AiAssistant_Error_ApiKeyRequiredDescription {
            get {
                return ResourceManager.GetString("AiAssistant_Error_ApiKeyRequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string AiAssistant_Error_ConnectionFailed {
            get {
                return ResourceManager.GetString("AiAssistant_Error_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to AI service. Please check your settings and try again..
        /// </summary>
        public static string AiAssistant_Error_ConnectionFailedDescription {
            get {
                return ResourceManager.GetString("AiAssistant_Error_ConnectionFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Failed.
        /// </summary>
        public static string AiAssistant_Error_RequestFailed {
            get {
                return ResourceManager.GetString("AiAssistant_Error_RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while processing your request: {0}.
        /// </summary>
        public static string AiAssistant_Error_RequestFailedDescription {
            get {
                return ResourceManager.GetString("AiAssistant_Error_RequestFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama Not Running.
        /// </summary>
        public static string AiAssistant_Error_OllamaNotRunning {
            get {
                return ResourceManager.GetString("AiAssistant_Error_OllamaNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure Ollama is installed and running on your system..
        /// </summary>
        public static string AiAssistant_Error_OllamaNotRunningDescription {
            get {
                return ResourceManager.GetString("AiAssistant_Error_OllamaNotRunningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string AiAssistant_Status_Processing {
            get {
                return ResourceManager.GetString("AiAssistant_Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string AiAssistant_Status_Ready {
            get {
                return ResourceManager.GetString("AiAssistant_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Conversation.
        /// </summary>
        public static string AiAssistant_ClearConversation {
            get {
                return ResourceManager.GetString("AiAssistant_ClearConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string AiAssistant_Copy {
            get {
                return ResourceManager.GetString("AiAssistant_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string AiAssistant_Copied {
            get {
                return ResourceManager.GetString("AiAssistant_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string AiAssistant_UserMessage {
            get {
                return ResourceManager.GetString("AiAssistant_UserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string AiAssistant_AssistantMessage {
            get {
                return ResourceManager.GetString("AiAssistant_AssistantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string AiAssistant_Retry {
            get {
                return ResourceManager.GetString("AiAssistant_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export History.
        /// </summary>
        public static string AiAssistant_ExportHistory {
            get {
                return ResourceManager.GetString("AiAssistant_ExportHistory", resourceCulture);
            }
        }
        
        public static string AiAssistant_ClearConversationConfirm {
            get {
                return ResourceManager.GetString("AiAssistant_ClearConversationConfirm", resourceCulture);
            }
        }
        
        public static string AiAssistant_ExportSuccess {
            get {
                return ResourceManager.GetString("AiAssistant_ExportSuccess", resourceCulture);
            }
        }
        
        public static string AiAssistant_ExportError {
            get {
                return ResourceManager.GetString("AiAssistant_ExportError", resourceCulture);
            }
        }
        
        public static string AiAssistant_NewConversation {
            get {
                return ResourceManager.GetString("AiAssistant_NewConversation", resourceCulture);
            }
        }
        
        public static string AiAssistant_NewSession {
            get {
                return ResourceManager.GetString("AiAssistant_NewSession", resourceCulture);
            }
        }
        
        public static string AiAssistant_DeleteSession {
            get {
                return ResourceManager.GetString("AiAssistant_DeleteSession", resourceCulture);
            }
        }
        
        public static string AiAssistant_DeleteSessionConfirm {
            get {
                return ResourceManager.GetString("AiAssistant_DeleteSessionConfirm", resourceCulture);
            }
        }
        
        public static string AiAssistant_Regenerate {
            get {
                return ResourceManager.GetString("AiAssistant_Regenerate", resourceCulture);
            }
        }
        
        public static string AiAssistant_PromptTemplates {
            get {
                return ResourceManager.GetString("AiAssistant_PromptTemplates", resourceCulture);
            }
        }
        
        public static string AiAssistant_Sessions {
            get {
                return ResourceManager.GetString("AiAssistant_Sessions", resourceCulture);
            }
        }
        
        public static string AiAssistant_Welcome {
            get {
                return ResourceManager.GetString("AiAssistant_Welcome", resourceCulture);
            }
        }
        
        public static string AiAssistant_WelcomeMessage {
            get {
                return ResourceManager.GetString("AiAssistant_WelcomeMessage", resourceCulture);
            }
        }
        
        public static string AiAssistant_GoodMorning {
            get {
                return ResourceManager.GetString("AiAssistant_GoodMorning", resourceCulture);
            }
        }
        
        public static string AiAssistant_GoodAfternoon {
            get {
                return ResourceManager.GetString("AiAssistant_GoodAfternoon", resourceCulture);
            }
        }
        
        public static string AiAssistant_GoodEvening {
            get {
                return ResourceManager.GetString("AiAssistant_GoodEvening", resourceCulture);
            }
        }
        
        public static string AiAssistant_GoodNight {
            get {
                return ResourceManager.GetString("AiAssistant_GoodNight", resourceCulture);
            }
        }
        
        public static string AiAssistant_NewChat {
            get {
                return ResourceManager.GetString("AiAssistant_NewChat", resourceCulture);
            }
        }
        
        public static string AiAssistant_HistoryChat {
            get {
                return ResourceManager.GetString("AiAssistant_HistoryChat", resourceCulture);
            }
        }
        
        public static string AiAssistant_HelpMeWrite {
            get {
                return ResourceManager.GetString("AiAssistant_HelpMeWrite", resourceCulture);
            }
        }
        
        public static string AiAssistant_AICreation {
            get {
                return ResourceManager.GetString("AiAssistant_AICreation", resourceCulture);
            }
        }
        
        public static string AiAssistant_AppGeneration {
            get {
                return ResourceManager.GetString("AiAssistant_AppGeneration", resourceCulture);
            }
        }
        
        public static string AiAssistant_CloudDrive {
            get {
                return ResourceManager.GetString("AiAssistant_CloudDrive", resourceCulture);
            }
        }
        
        public static string AiAssistant_More {
            get {
                return ResourceManager.GetString("AiAssistant_More", resourceCulture);
            }
        }
        
        public static string AiAssistant_SendMessageOrSelectSkill {
            get {
                return ResourceManager.GetString("AiAssistant_SendMessageOrSelectSkill", resourceCulture);
            }
        }
        
        public static string AiAssistant_DeepThinking {
            get {
                return ResourceManager.GetString("AiAssistant_DeepThinking", resourceCulture);
            }
        }
        
        public static string AiAssistant_QuickWrite {
            get {
                return ResourceManager.GetString("AiAssistant_QuickWrite", resourceCulture);
            }
        }
        
        public static string AiAssistant_QuickTranslate {
            get {
                return ResourceManager.GetString("AiAssistant_QuickTranslate", resourceCulture);
            }
        }
        
        public static string AiAssistant_QuickCode {
            get {
                return ResourceManager.GetString("AiAssistant_QuickCode", resourceCulture);
            }
        }
        
        public static string AiAssistant_QuickSearch {
            get {
                return ResourceManager.GetString("AiAssistant_QuickSearch", resourceCulture);
            }
        }
        
        public static string AiAssistant_QuickDocument {
            get {
                return ResourceManager.GetString("AiAssistant_QuickDocument", resourceCulture);
            }
        }
        
        public static string AiAssistant_QuickSummarize {
            get {
                return ResourceManager.GetString("AiAssistant_QuickSummarize", resourceCulture);
            }
        }
        
        public static string AiAssistant_QuickMore {
            get {
                return ResourceManager.GetString("AiAssistant_QuickMore", resourceCulture);
            }
        }
        
        public static string AiAssistant_Edit {
            get {
                return ResourceManager.GetString("AiAssistant_Edit", resourceCulture);
            }
        }
        
        public static string AiAssistant_Voice {
            get {
                return ResourceManager.GetString("AiAssistant_Voice", resourceCulture);
            }
        }
        
        public static string AiAssistant_FeatureComingSoon {
            get {
                return ResourceManager.GetString("AiAssistant_FeatureComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Response.
        /// </summary>
        public static string AiAssistant_CopyResponse {
            get {
                return ResourceManager.GetString("AiAssistant_CopyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string AiAssistant_Clear {
            get {
                return ResourceManager.GetString("AiAssistant_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-start Ollama Service.
        /// </summary>
        public static string AiAssistant_AutoStartOllama {
            get {
                return ResourceManager.GetString("AiAssistant_AutoStartOllama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Built-in Ollama.
        /// </summary>
        public static string AiAssistant_UseBuiltInOllama {
            get {
                return ResourceManager.GetString("AiAssistant_UseBuiltInOllama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama Executable Path:.
        /// </summary>
        public static string AiAssistant_OllamaExecutablePath {
            get {
                return ResourceManager.GetString("AiAssistant_OllamaExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string AiAssistant_Browse {
            get {
                return ResourceManager.GetString("AiAssistant_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ollama Executable.
        /// </summary>
        public static string AiAssistant_BrowseOllamaExecutable {
            get {
                return ResourceManager.GetString("AiAssistant_BrowseOllamaExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Ollama....
        /// </summary>
        public static string AiAssistant_Status_StartingOllama {
            get {
                return ResourceManager.GetString("AiAssistant_Status_StartingOllama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Start Ollama.
        /// </summary>
        public static string AiAssistant_Error_OllamaStartFailed {
            get {
                return ResourceManager.GetString("AiAssistant_Error_OllamaStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Ollama service. Please check if Ollama is installed and the executable path is correct..
        /// </summary>
        public static string AiAssistant_Error_OllamaStartFailedDescription {
            get {
                return ResourceManager.GetString("AiAssistant_Error_OllamaStartFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string AiAssistant_Downloading {
            get {
                return ResourceManager.GetString("AiAssistant_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Speed: {0} MB/s.
        /// </summary>
        public static string AiAssistant_DownloadSpeed {
            get {
                return ResourceManager.GetString("AiAssistant_DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining: {0}.
        /// </summary>
        public static string AiAssistant_TimeRemaining {
            get {
                return ResourceManager.GetString("AiAssistant_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Download.
        /// </summary>
        public static string AiAssistant_CancelDownload {
            get {
                return ResourceManager.GetString("AiAssistant_CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI is thinking....
        /// </summary>
        public static string AiAssistant_AIThinking {
            get {
                return ResourceManager.GetString("AiAssistant_AIThinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing....
        /// </summary>
        public static string AiAssistant_AITyping {
            get {
                return ResourceManager.GetString("AiAssistant_AITyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string AiAssistant_LikeMessage {
            get {
                return ResourceManager.GetString("AiAssistant_LikeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string AiAssistant_MessageLiked {
            get {
                return ResourceManager.GetString("AiAssistant_MessageLiked", resourceCulture);
            }
        }
    }
}

