//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugins.DockLauncher
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Plugins.DockLauncher.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Launcher.
        /// </summary>
        public static string DockLauncher_PageTitle {
            get {
                return ResourceManager.GetString("DockLauncher_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to macOS-style dock launcher for quick application access and window management.
        /// </summary>
        public static string DockLauncher_PageDescription {
            get {
                return ResourceManager.GetString("DockLauncher_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dock.
        /// </summary>
        public static string DockLauncher_EnableDock {
            get {
                return ResourceManager.GetString("DockLauncher_EnableDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the dock launcher at the bottom of the screen.
        /// </summary>
        public static string DockLauncher_EnableDockDescription {
            get {
                return ResourceManager.GetString("DockLauncher_EnableDockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Application.
        /// </summary>
        public static string DockLauncher_AddApplication {
            get {
                return ResourceManager.GetString("DockLauncher_AddApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DockLauncher_RemoveApplication {
            get {
                return ResourceManager.GetString("DockLauncher_RemoveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Size.
        /// </summary>
        public static string DockLauncher_IconSize {
            get {
                return ResourceManager.GetString("DockLauncher_IconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        public static string DockLauncher_AutoHide {
            get {
                return ResourceManager.GetString("DockLauncher_AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically hide the dock when mouse leaves.
        /// </summary>
        public static string DockLauncher_AutoHideDescription {
            get {
                return ResourceManager.GetString("DockLauncher_AutoHideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide Delay (seconds).
        /// </summary>
        public static string DockLauncher_AutoHideDelay {
            get {
                return ResourceManager.GetString("DockLauncher_AutoHideDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string DockLauncher_Applications {
            get {
                return ResourceManager.GetString("DockLauncher_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No applications added to dock.
        /// </summary>
        public static string DockLauncher_NoApplications {
            get {
                return ResourceManager.GetString("DockLauncher_NoApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string DockLauncher_Settings {
            get {
                return ResourceManager.GetString("DockLauncher_Settings", resourceCulture);
            }
        }
    }
}


